-- canon_seed v1 — the Realm Graph's curated canon anchors
-- (spec: docs/superpowers/specs/2026-07-31-realm-graph-master-plan.md section 5).
-- Compiled 2026-08-01 from recognized award/canon lists, each row verified against
-- the cited source page (source_detail carries the citation) and matched to the
-- production catalog by title (media_id = catalog/AniList id). A title honored by
-- N sources appears as N rows (one per source/category). Editorial data only.
-- Row counts per source at compile time:
--   Annecy Cristal: 3
--   Critic Consensus: 25
--   Eisner Award: 22
--   Japan Media Arts Festival: 118
--   Kodansha Manga Award: 46
--   Kono Manga ga Sugoi!: 39
--   Manga Taishō: 19
--   Shogakukan Manga Award: 47
--   Tezuka Cultural Prize: 27
--   Tokyo Anime Award: 39
--   r/anime Classics: 50
--   TOTAL: 435

create table if not exists public.canon_seed (
  id bigint generated always as identity primary key,
  media_type text not null check (media_type in ('ANIME','MANGA')),
  media_id integer not null,
  title text not null,
  source text not null,
  source_detail text,
  year integer,
  category text not null default '',
  unique (media_type, media_id, source, category)
);

-- Editorial reference data: everyone reads, nobody writes through the API
-- (writes happen via migrations / service role, which bypasses RLS).
alter table public.canon_seed enable row level security;

drop policy if exists canon_seed_public_read on public.canon_seed;
create policy canon_seed_public_read
  on public.canon_seed
  for select
  using (true);

create index if not exists canon_seed_media_idx
  on public.canon_seed (media_type, media_id);

insert into public.canon_seed (media_type, media_id, title, source, source_detail, year, category) values
  ('ANIME', 1184, 'Porco Rosso', 'Annecy Cristal', 'Annecy 1993 — Cristal du long métrage · https://en.wikipedia.org/wiki/Annecy_International_Animation_Film_Festival', 1993, 'Cristal — Feature Film'),
  ('ANIME', 2310, 'Pom Poko', 'Annecy Cristal', 'Annecy 1995 — Cristal du long métrage · https://en.wikipedia.org/wiki/Annecy_International_Animation_Film_Festival', 1995, 'Cristal — Feature Film'),
  ('ANIME', 13272, 'Lu over the Wall', 'Annecy Cristal', 'Annecy 2017 — Cristal du long métrage · https://en.wikipedia.org/wiki/Annecy_International_Animation_Film_Festival', 2017, 'Cristal — Feature Film'),
  ('ANIME', 297, 'Akira', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#13); Paste, The 100 Best Anime Movies of All Time (#1) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1331, 'Angel''s Egg', 'Critic Consensus', 'Paste, The 100 Best Anime Movies of All Time (#73) · https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 13293, 'Belladonna of Sadness', 'Critic Consensus', 'Paste, The 100 Best Anime Movies of All Time (#19) · https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 551, 'Castle in the Sky', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#87); Paste, The 100 Best Anime Movies of All Time (#38) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 117, 'Cowboy Bebop', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#1) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 318, 'FLCL', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#4) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 419, 'Ghost in the Shell', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#85); Paste, The 100 Best Anime Movies of All Time (#5) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 336, 'Grave of the Fireflies', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#15); Paste, The 100 Best Anime Movies of All Time (#4) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 375, 'Kiki''s Delivery Service', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#49); Paste, The 100 Best Anime Movies of All Time (#32) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 2282, 'Lupin III: The Castle of Cagliostro', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#51); Paste, The 100 Best Anime Movies of All Time (#59) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1338, 'Millennium Actress', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#99); Paste, The 100 Best Anime Movies of All Time (#18) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 12909, 'Mind Game', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#59); Paste, The 100 Best Anime Movies of All Time (#21) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1746, 'Mobile Suit Gundam', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#16) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 221, 'My Neighbor Totoro', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#4); Paste, The 100 Best Anime Movies of All Time (#10) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 856, 'Nausicaä of the Valley of the Wind', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#96); Paste, The 100 Best Anime Movies of All Time (#25) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 110, 'Neon Genesis Evangelion', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#2) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 486, 'Paprika', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#79); Paste, The 100 Best Anime Movies of All Time (#6) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 286, 'Perfect Blue', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#97); Paste, The 100 Best Anime Movies of All Time (#8) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 200, 'Princess Mononoke', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#30); Paste, The 100 Best Anime Movies of All Time (#13) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1131, 'Revolutionary Girl Utena', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#3) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 3340, 'Royal Space Force: The Wings of Honnêamise', 'Critic Consensus', 'Paste, The 100 Best Anime Movies of All Time (#12) · https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 269, 'Serial Experiments Lain', 'Critic Consensus', 'The A.V. Club, The 35 Best Anime of All Time (#17) · https://www.avclub.com/best-anime-of-all-time', null, 'Landmark'),
  ('ANIME', 111, 'Spirited Away', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#2); Paste, The 100 Best Anime Movies of All Time (#2) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1225, 'The Tale of Princess Kaguya', 'Critic Consensus', 'Paste, The 100 Best Anime Movies of All Time (#69) · https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('ANIME', 1017, 'Tokyo Godfathers', 'Critic Consensus', 'Time Out, The 100 Best Animated Movies (#57); Paste, The 100 Best Anime Movies of All Time (#31) · https://www.timeout.com/film/best-animated-movies | https://www.pastemagazine.com/movies/best-anime-movies/the-100-best-anime-movies-of-all-time', null, 'Landmark'),
  ('MANGA', 1552, 'Gon Swimmin''', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'' (1998) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 1998, 'Best U.S. Edition — Asia'),
  ('MANGA', 58526, 'Star Wars: A New Hope--Manga', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'' (1999) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 1999, 'Best U.S. Edition — Asia'),
  ('MANGA', 273, 'Blade of the Immortal', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'' (2000) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 2000, 'Best U.S. Edition — Asia'),
  ('MANGA', 511, 'Lone Wolf and Cub', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'' (2001) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 2001, 'Best U.S. Edition — Asia'),
  ('MANGA', 169, 'Akira', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'' (2002) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 2002, 'Best U.S. Edition — Asia'),
  ('MANGA', 2051, 'Buddha', 'Eisner Award', 'predecessor category ''Best U.S. Edition of Foreign Material'', vols. 1 and 2 (2004) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material', 2004, 'Best U.S. Edition — Asia'),
  ('MANGA', 1873, 'Old Boy', 'Eisner Award', 'then named ''Best U.S. Edition of International Material–Japan'' (2007) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2007, 'Best U.S. Edition — Asia'),
  ('MANGA', 1810, 'Tekkonkinkreet: Black & White', 'Eisner Award', 'then named ''Best U.S. Edition of International Material–Japan'' (2008) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2008, 'Best U.S. Edition — Asia'),
  ('MANGA', 1637, 'Dororo', 'Eisner Award', 'then named ''Best U.S. Edition of International Material–Japan'' (2009) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2009, 'Best U.S. Edition — Asia'),
  ('MANGA', 3627, 'A Drifting Life', 'Eisner Award', 'Eisner Award (2010) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2010, 'Best U.S. Edition — Asia'),
  ('MANGA', 30, 'Naoki Urasawa''s 20th Century Boys', 'Eisner Award', 'Eisner Award (2011) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2011, 'Best U.S. Edition — Asia'),
  ('MANGA', 6439, 'Onward Towards Our Noble Deaths', 'Eisner Award', 'Eisner Award (2012) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2012, 'Best U.S. Edition — Asia'),
  ('MANGA', 55863, 'The Mysterious Underground Men', 'Eisner Award', 'Eisner Award (2014) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2014, 'Best U.S. Edition — Asia'),
  ('MANGA', 7699, 'Showa: A History of Japan', 'Eisner Award', 'Eisner Award (2015) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2015, 'Best U.S. Edition — Asia'),
  ('MANGA', 2063, 'My Brother''s Husband', 'Eisner Award', 'Eisner Award, vol. 1 (2018) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2018, 'Best U.S. Edition — Asia'),
  ('MANGA', 3500, 'Tokyo Tarareba Girls', 'Eisner Award', 'Eisner Award (2019) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2019, 'Best U.S. Edition — Asia'),
  ('MANGA', 4032, 'Cats of the Louvre', 'Eisner Award', 'Eisner Award, tie (2020) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2020, 'Best U.S. Edition — Asia'),
  ('MANGA', 108, 'Witch Hat Atelier', 'Eisner Award', 'Eisner Award, tie (2020) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2020, 'Best U.S. Edition — Asia'),
  ('MANGA', 792, 'Remina', 'Eisner Award', 'Eisner Award (2021) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2021, 'Best U.S. Edition — Asia'),
  ('MANGA', 6626, 'Lovesickness: Junji Ito Story Collection', 'Eisner Award', 'Eisner Award (2022) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2022, 'Best U.S. Edition — Asia'),
  ('MANGA', 18129, 'Shuna''s Journey', 'Eisner Award', 'Eisner Award (2023) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2023, 'Best U.S. Edition — Asia'),
  ('MANGA', 6498, 'Tokyo These Days', 'Eisner Award', 'Eisner Award (2025) · https://en.wikipedia.org/wiki/Eisner_Award_for_Best_U.S._Edition_of_International_Material%E2%80%94Asia', 2025, 'Best U.S. Edition — Asia'),
  ('ANIME', 48367, 'Donguri’s House', 'Japan Media Arts Festival', '1st Festival (1997) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/1st/animation/index-2.html', 1997, 'Animation Excellence Award'),
  ('ANIME', 33098, 'Mini Cartoon～Knyacki～', 'Japan Media Arts Festival', '1st Festival (1997) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/1st/animation/index-2.html', 1997, 'Animation Excellence Award'),
  ('ANIME', 110, 'Neon Genesis Evangelion', 'Japan Media Arts Festival', '1st Festival (1997) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/1st/animation/index-2.html', 1997, 'Animation Excellence Award'),
  ('ANIME', 7709, 'Doraemon Nobita’s South Sea Adventure', 'Japan Media Arts Festival', '2nd Festival (1998) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/2nd/animation/index-2.html', 1998, 'Animation Excellence Award'),
  ('ANIME', 33496, 'believe in it', 'Japan Media Arts Festival', '2nd Festival (1998) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/2nd/animation/index-2.html', 1998, 'Animation Excellence Award'),
  ('ANIME', 269, 'serial experiments lain', 'Japan Media Arts Festival', '2nd Festival (1998) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/2nd/animation/index-2.html', 1998, 'Animation Excellence Award'),
  ('ANIME', 31212, 'MOTHER', 'Japan Media Arts Festival', '3rd Festival (1999) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/3rd/animation/index-2.html', 1999, 'Animation Excellence Award'),
  ('ANIME', 3002, 'My Neighbors the Yamadas', 'Japan Media Arts Festival', '3rd Festival (1999) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/3rd/animation/index-2.html', 1999, 'Animation Excellence Award'),
  ('ANIME', 30251, 'OJARUMARU 2', 'Japan Media Arts Festival', '3rd Festival (1999) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/3rd/animation/index-2.html', 1999, 'Animation Excellence Award'),
  ('ANIME', 95631, 'TYO STORY', 'Japan Media Arts Festival', '3rd Festival (1999) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/3rd/animation/index-2.html', 1999, 'Animation Excellence Award'),
  ('ANIME', 6912, 'HIDAMARI NO KI', 'Japan Media Arts Festival', '4th Festival (2000) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/4th/animation/index-2.html', 2000, 'Animation Excellence Award'),
  ('ANIME', 13265, 's.o.s', 'Japan Media Arts Festival', '4th Festival (2000) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/4th/animation/index-2.html', 2000, 'Animation Excellence Award'),
  ('ANIME', 12982, 'Nekojiru-So', 'Japan Media Arts Festival', '5th Festival (2001) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/5th/animation/index-2.html', 2001, 'Animation Excellence Award'),
  ('ANIME', 32766, 'Nostalgia', 'Japan Media Arts Festival', '5th Festival (2001) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/5th/animation/index-2.html', 2001, 'Animation Excellence Award'),
  ('ANIME', 16393, 'Abenobashi Maho Shotengai', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/animation/index-2.html', 2002, 'Animation Excellence Award'),
  ('ANIME', 1102, 'GHOST IN THE SHELL: STAND ALONE COMPLEX', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/animation/index-2.html', 2002, 'Animation Excellence Award'),
  ('ANIME', 7382, 'Mt. Head', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/animation/index-2.html', 2002, 'Animation Excellence Award'),
  ('ANIME', 1127, 'The Cat Returns', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/animation/index-2.html', 2002, 'Animation Excellence Award'),
  ('ANIME', 80484, 'GA-RA-KU-TA Mr.Stain on Junk Alley', 'Japan Media Arts Festival', '7th Festival (2003) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/7th/animation/index-2.html', 2003, 'Animation Excellence Award'),
  ('ANIME', 68115, 'KOMANEKO-The First Step-', 'Japan Media Arts Festival', '7th Festival (2003) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/7th/animation/index-2.html', 2003, 'Animation Excellence Award'),
  ('ANIME', 1017, 'TOKYO GOD FATHERS', 'Japan Media Arts Festival', '7th Festival (2003) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/7th/animation/index-2.html', 2003, 'Animation Excellence Award'),
  ('ANIME', 33074, 'ACIDMAN short film “SAI (Part 1) / Revolving…to the core”', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/animation/index-2.html', 2004, 'Animation Excellence Award'),
  ('ANIME', 45906, 'BIRTHDAY BOY', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/animation/index-2.html', 2004, 'Animation Excellence Award'),
  ('ANIME', 161, 'HOWL’S MOVING CASTLE', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/animation/index-2.html', 2004, 'Animation Excellence Award'),
  ('ANIME', 9735, 'MAKASETE IRUKA!', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/animation/index-2.html', 2004, 'Animation Excellence Award'),
  ('ANIME', 2736, 'Kamichu!', 'Japan Media Arts Festival', '9th Festival (2005) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/9th/animation/index-2.html', 2005, 'Animation Excellence Award'),
  ('ANIME', 29889, 'THE BOOK OF THE DEAD', 'Japan Media Arts Festival', '9th Festival (2005) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/9th/animation/index-2.html', 2005, 'Animation Excellence Award'),
  ('ANIME', 10324, 'The Old Crocodile', 'Japan Media Arts Festival', '9th Festival (2005) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/9th/animation/index-2.html', 2005, 'Animation Excellence Award'),
  ('ANIME', 68223, 'A COUNTRY BETWEEN THE WORLD', 'Japan Media Arts Festival', '10th Festival (2006) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/10th/animation/index-2.html', 2006, 'Animation Excellence Award'),
  ('ANIME', 69026, 'Bloomed Words', 'Japan Media Arts Festival', '10th Festival (2006) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/10th/animation/index-2.html', 2006, 'Animation Excellence Award'),
  ('ANIME', 33214, 'PIKA PIKA', 'Japan Media Arts Festival', '10th Festival (2006) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/10th/animation/index-2.html', 2006, 'Animation Excellence Award'),
  ('ANIME', 1814, 'CyberCoil/DENNOU COIL', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/animation/index-2.html', 2007, 'Animation Excellence Award'),
  ('ANIME', 4805, 'Franz Kafka’s A COUNTRY DOCTOR', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/animation/index-2.html', 2007, 'Animation Excellence Award'),
  ('ANIME', 155, 'GURREN LAGANN', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/animation/index-2.html', 2007, 'Animation Excellence Award'),
  ('ANIME', 67462, 'Ukkari Penelope', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/animation/index-2.html', 2007, 'Animation Excellence Award'),
  ('ANIME', 31109, 'A Child’s Metaphysics', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/animation/index-2.html', 2008, 'Animation Excellence Award'),
  ('ANIME', 31227, 'DREAMS', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/animation/index-2.html', 2008, 'Animation Excellence Award'),
  ('ANIME', 1643, 'KAIBA', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/animation/index-2.html', 2008, 'Animation Excellence Award'),
  ('ANIME', 50043, 'KUDAN', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/animation/index-2.html', 2008, 'Animation Excellence Award'),
  ('ANIME', 9473, 'ELEMI', 'Japan Media Arts Festival', '13th Festival (2009) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/13th/animation/index-2.html', 2009, 'Animation Excellence Award'),
  ('ANIME', 1199, 'Tokyo Magnitude 8.0', 'Japan Media Arts Festival', '13th Festival (2009) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/13th/animation/index-2.html', 2009, 'Animation Excellence Award'),
  ('ANIME', 1506, 'Colorful', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/animation/index-2.html', 2010, 'Animation Excellence Award'),
  ('ANIME', 4430, 'Fumiko’s Confession', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/animation/index-2.html', 2010, 'Animation Excellence Award'),
  ('ANIME', 31037, 'In a pig’s eye', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/animation/index-2.html', 2010, 'Animation Excellence Award'),
  ('ANIME', 5404, 'Mai Mai Miracle', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/animation/index-2.html', 2010, 'Animation Excellence Award'),
  ('ANIME', 13289, 'A Letter to Momo', 'Japan Media Arts Festival', '15th Festival (2011) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/15th/animation/index-2.html', 2011, 'Animation Excellence Award'),
  ('ANIME', 6462, 'Legend of the Millennium Dragon', 'Japan Media Arts Festival', '15th Festival (2011) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/15th/animation/index-2.html', 2011, 'Animation Excellence Award'),
  ('ANIME', 29660, 'Muybridge’s Strings', 'Japan Media Arts Festival', '15th Festival (2011) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/15th/animation/index-2.html', 2011, 'Animation Excellence Award'),
  ('ANIME', 4803, 'ASURA', 'Japan Media Arts Festival', '16th Festival (2012) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/16th/animation/index-2.html', 2012, 'Animation Excellence Award'),
  ('ANIME', 31767, 'The Great Rabbit', 'Japan Media Arts Festival', '16th Festival (2012) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/16th/animation/index-2.html', 2012, 'Animation Excellence Award')
on conflict (media_type, media_id, source, category) do nothing;

insert into public.canon_seed (media_type, media_id, title, source, source_detail, year, category) values
  ('ANIME', 7529, 'The Life of Budori Gusuko', 'Japan Media Arts Festival', '16th Festival (2012) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/16th/animation/index-2.html', 2012, 'Animation Excellence Award'),
  ('ANIME', 334, 'WOLF CHILDREN', 'Japan Media Arts Festival', '16th Festival (2012) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/16th/animation/index-2.html', 2012, 'Animation Excellence Award'),
  ('ANIME', 769, 'EVANGELION:3.33 YOU CAN (NOT) REDO.', 'Japan Media Arts Festival', '17th Festival (2013) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/17th/animation/index-2.html', 2013, 'Animation Excellence Award'),
  ('ANIME', 236, 'Golden Time', 'Japan Media Arts Festival', '17th Festival (2013) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/17th/animation/index-2.html', 2013, 'Animation Excellence Award'),
  ('ANIME', 1096, 'Patema Inverted', 'Japan Media Arts Festival', '17th Festival (2013) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/17th/animation/index-2.html', 2013, 'Animation Excellence Award'),
  ('ANIME', 1630, 'The Eccentric Family', 'Japan Media Arts Festival', '17th Festival (2013) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/17th/animation/index-2.html', 2013, 'Animation Excellence Award'),
  ('ANIME', 7224, 'Crayon Shin-chan: Serious Battle! Robot Dad Strikes Back', 'Japan Media Arts Festival', '18th Festival (2014) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/18th/animation/index-2.html', 2014, 'Animation Excellence Award'),
  ('ANIME', 4255, 'Giovanni’s Island', 'Japan Media Arts Festival', '18th Festival (2014) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/18th/animation/index-2.html', 2014, 'Animation Excellence Award'),
  ('ANIME', 48723, 'My Home', 'Japan Media Arts Festival', '19th Festival (2015) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/19th/animation/index-2.html', 2015, 'Animation Excellence Award'),
  ('ANIME', 2845, 'The Case of Hana & Alice', 'Japan Media Arts Festival', '19th Festival (2015) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/19th/animation/index-2.html', 2015, 'Animation Excellence Award'),
  ('ANIME', 4208, 'The Master', 'Japan Media Arts Festival', '19th Festival (2015) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/19th/animation/index-2.html', 2015, 'Animation Excellence Award'),
  ('ANIME', 16, 'A Silent Voice', 'Japan Media Arts Festival', '20th Festival (2017) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/20th/animation/index-2.html', 2017, 'Animation Excellence Award'),
  ('ANIME', 4694, 'Among the black waves', 'Japan Media Arts Festival', '20th Festival (2017) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/20th/animation/index-2.html', 2017, 'Animation Excellence Award'),
  ('ANIME', 6874, 'COCOLORS', 'Japan Media Arts Festival', '21st Festival (2018) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/21st/animation/index-2.html', 2018, 'Animation Excellence Award'),
  ('ANIME', 50246, 'Harmonia feat. Makoto', 'Japan Media Arts Festival', '21st Festival (2018) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/21st/animation/index-2.html', 2018, 'Animation Excellence Award'),
  ('ANIME', 12927, 'DRAGON PILOT: Hisone & Masotan', 'Japan Media Arts Festival', '22nd Festival (2019) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/22nd/animation/index-2.html', 2019, 'Animation Excellence Award'),
  ('ANIME', 4466, 'OKKO’S Inn', 'Japan Media Arts Festival', '22nd Festival (2019) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/22nd/animation/index-2.html', 2019, 'Animation Excellence Award'),
  ('ANIME', 1910, 'Penguin Highway', 'Japan Media Arts Festival', '22nd Festival (2019) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/22nd/animation/index-2.html', 2019, 'Animation Excellence Award'),
  ('ANIME', 44752, 'A Japanese Boy Who Draws', 'Japan Media Arts Festival', '23rd Festival (2020) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/23rd/animation/index-2.html', 2020, 'Animation Excellence Award'),
  ('ANIME', 31272, 'GON, THE LITTLE FOX', 'Japan Media Arts Festival', '23rd Festival (2020) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/23rd/animation/index-2.html', 2020, 'Animation Excellence Award'),
  ('ANIME', 368, 'A Whisker Away', 'Japan Media Arts Festival', '24th Festival (2021) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/24th/animation/index-2.html', 2021, 'Animation Excellence Award'),
  ('ANIME', 10078, 'Grey to Green', 'Japan Media Arts Festival', '24th Festival (2021) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/24th/animation/index-2.html', 2021, 'Animation Excellence Award'),
  ('ANIME', 345, 'Violet Evergarden: the Movie', 'Japan Media Arts Festival', '24th Festival (2021) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/24th/animation/index-2.html', 2021, 'Animation Excellence Award'),
  ('ANIME', 8914, 'Dozens of Norths', 'Japan Media Arts Festival', '25th Festival (2022) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/25th/animation/index-2.html', 2022, 'Animation Excellence Award'),
  ('ANIME', 5433, 'FORTUNE FAVORS LADY NIKUKO', 'Japan Media Arts Festival', '25th Festival (2022) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/25th/animation/index-2.html', 2022, 'Animation Excellence Award'),
  ('ANIME', 739, 'Sonny Boy', 'Japan Media Arts Festival', '25th Festival (2022) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/25th/animation/index-2.html', 2022, 'Animation Excellence Award'),
  ('ANIME', 200, 'Princess Mononoke', 'Japan Media Arts Festival', '1st Festival (1997) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/1st/animation/index-2.html', 1997, 'Animation Grand Prize'),
  ('ANIME', 6377, 'Glassy Ocean', 'Japan Media Arts Festival', '2nd Festival (1998) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/2nd/animation/index-2.html', 1998, 'Animation Grand Prize'),
  ('ANIME', 13185, 'BLOOD THE LAST VAMPIRE', 'Japan Media Arts Festival', '4th Festival (2000) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/4th/animation/index-2.html', 2000, 'Animation Grand Prize'),
  ('ANIME', 1338, 'Millennium Actress', 'Japan Media Arts Festival', '5th Festival (2001) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/5th/animation/index-2.html', 2001, 'Animation Grand Prize'),
  ('ANIME', 111, 'Spirited Away', 'Japan Media Arts Festival', '5th Festival (2001) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/5th/animation/index-2.html', 2001, 'Animation Grand Prize'),
  ('ANIME', 7931, 'The Storm Called: The Battle of the Warring States', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/animation/index-2.html', 2002, 'Animation Grand Prize'),
  ('ANIME', 8908, 'The Winter Days', 'Japan Media Arts Festival', '7th Festival (2003) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/7th/animation/index-2.html', 2003, 'Animation Grand Prize'),
  ('ANIME', 12909, 'Mind Game', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/animation/index-2.html', 2004, 'Animation Grand Prize'),
  ('ANIME', 80900, 'Flow', 'Japan Media Arts Festival', '9th Festival (2005) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/9th/animation/index-2.html', 2005, 'Animation Grand Prize'),
  ('ANIME', 390, 'The Girl Who Leapt Through Time', 'Japan Media Arts Festival', '10th Festival (2006) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/10th/animation/index-2.html', 2006, 'Animation Grand Prize'),
  ('ANIME', 5645, 'Summer Days with Coo', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/animation/index-2.html', 2007, 'Animation Grand Prize'),
  ('ANIME', 22450, 'The House of Small Cubes', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/animation/index-2.html', 2008, 'Animation Grand Prize'),
  ('ANIME', 798, 'Summer Wars', 'Japan Media Arts Festival', '13th Festival (2009) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/13th/animation/index-2.html', 2009, 'Animation Grand Prize'),
  ('ANIME', 481, 'The Tatami Galaxy', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/animation/index-2.html', 2010, 'Animation Grand Prize'),
  ('ANIME', 180, 'Puella Magi Madoka Magica', 'Japan Media Arts Festival', '15th Festival (2011) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/15th/animation/index-2.html', 2011, 'Animation Grand Prize'),
  ('ANIME', 5262, 'COMBUSTIBLE', 'Japan Media Arts Festival', '16th Festival (2012) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/16th/animation/index-2.html', 2012, 'Animation Grand Prize'),
  ('ANIME', 15, 'your name.', 'Japan Media Arts Festival', '20th Festival (2017) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/20th/animation/index-2.html', 2017, 'Animation Grand Prize'),
  ('ANIME', 1327, 'In This Corner of the World', 'Japan Media Arts Festival', '21st Festival (2018) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/21st/animation/index-2.html', 2018, 'Animation Grand Prize'),
  ('ANIME', 13272, 'Lu over the wall', 'Japan Media Arts Festival', '21st Festival (2018) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/21st/animation/index-2.html', 2018, 'Animation Grand Prize'),
  ('ANIME', 1540, 'Children of the Sea', 'Japan Media Arts Festival', '23rd Festival (2020) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/23rd/animation/index-2.html', 2020, 'Animation Grand Prize'),
  ('ANIME', 784, 'Keep Your Hands Off Eizouken!', 'Japan Media Arts Festival', '24th Festival (2021) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/24th/animation/index-2.html', 2021, 'Animation Grand Prize'),
  ('MANGA', 62195, 'I’m home', 'Japan Media Arts Festival', '3rd Festival (1999) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/3rd/manga/index-2.html', 1999, 'Manga Grand Prize'),
  ('MANGA', 14, 'Vagabond', 'Japan Media Arts Festival', '4th Festival (2000) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/4th/manga/index-2.html', 2000, 'Manga Grand Prize'),
  ('MANGA', 70169, 'A Day in the Life of Mr. F', 'Japan Media Arts Festival', '5th Festival (2001) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/5th/manga/index-2.html', 2001, 'Manga Grand Prize'),
  ('MANGA', 26328, 'Sexy Voice and Robo', 'Japan Media Arts Festival', '6th Festival (2002) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/6th/manga/index-2.html', 2002, 'Manga Grand Prize'),
  ('MANGA', 3044, 'Town of Evening Calm, Country of Cherry Blossoms', 'Japan Media Arts Festival', '8th Festival (2004) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/8th/manga/index-2.html', 2004, 'Manga Grand Prize'),
  ('MANGA', 7879, 'Disappearance Diary', 'Japan Media Arts Festival', '9th Festival (2005) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/9th/manga/index-2.html', 2005, 'Manga Grand Prize'),
  ('MANGA', 28766, 'A Spirit of the Sun', 'Japan Media Arts Festival', '10th Festival (2006) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/10th/manga/index-2.html', 2006, 'Manga Grand Prize'),
  ('MANGA', 63649, 'Mori no Asagao', 'Japan Media Arts Festival', '11th Festival (2007) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/11th/manga/index-2.html', 2007, 'Manga Grand Prize'),
  ('MANGA', 2101, 'Piano Forest', 'Japan Media Arts Festival', '12th Festival (2008) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/12th/manga/index-2.html', 2008, 'Manga Grand Prize'),
  ('MANGA', 16, 'Vinland Saga', 'Japan Media Arts Festival', '13th Festival (2009) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/13th/manga/index-2.html', 2009, 'Manga Grand Prize'),
  ('MANGA', 1238, 'Historiē', 'Japan Media Arts Festival', '14th Festival (2010) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/14th/manga/index-2.html', 2010, 'Manga Grand Prize'),
  ('MANGA', 4209, 'Saturn Apartments', 'Japan Media Arts Festival', '15th Festival (2011) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/15th/manga/index-2.html', 2011, 'Manga Grand Prize'),
  ('MANGA', 127, 'JOJOLION -Jojo’s Bizarre Adventure Part8-', 'Japan Media Arts Festival', '17th Festival (2013) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/17th/manga/index-2.html', 2013, 'Manga Grand Prize'),
  ('MANGA', 30525, 'The Five-colored Boat', 'Japan Media Arts Festival', '18th Festival (2014) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/18th/manga/index-2.html', 2014, 'Manga Grand Prize'),
  ('MANGA', 862, 'So-and-so, Such-and-such', 'Japan Media Arts Festival', '19th Festival (2015) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/19th/manga/index-2.html', 2015, 'Manga Grand Prize'),
  ('MANGA', 884, 'BLUE GIANT', 'Japan Media Arts Festival', '20th Festival (2017) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/20th/manga/index-2.html', 2017, 'Manga Grand Prize'),
  ('MANGA', 1784, 'My Dear, Mom', 'Japan Media Arts Festival', '21st Festival (2018) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/21st/manga/index-2.html', 2018, 'Manga Grand Prize'),
  ('MANGA', 772, 'ORIGIN', 'Japan Media Arts Festival', '22nd Festival (2019) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/22nd/manga/index-2.html', 2019, 'Manga Grand Prize'),
  ('MANGA', 12405, 'Prehistory of Robo Sapiens', 'Japan Media Arts Festival', '23rd Festival (2020) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/23rd/manga/index-2.html', 2020, 'Manga Grand Prize'),
  ('MANGA', 253, 'March comes in like a lion', 'Japan Media Arts Festival', '24th Festival (2021) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/24th/manga/index-2.html', 2021, 'Manga Grand Prize'),
  ('MANGA', 98273, 'Golden Raspberry', 'Japan Media Arts Festival', '25th Festival (2022) · https://j-mediaarts-festival.bunka.go.jp/en/award/previous/25th/manga/index-2.html', 2022, 'Manga Grand Prize'),
  ('MANGA', 169, 'Akira', 'Kodansha Manga Award', '8th award (1984) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1984, 'General Category'),
  ('MANGA', 1131, 'Adolf', 'Kodansha Manga Award', '10th award (1986) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1986, 'General Category'),
  ('MANGA', 52001, 'What''s Michael?', 'Kodansha Manga Award', '10th award (1986) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1986, 'General Category'),
  ('MANGA', 69819, 'Actor', 'Kodansha Manga Award', '11th award (1987) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1987, 'General Category'),
  ('MANGA', 8972, 'Be-Bop High School', 'Kodansha Manga Award', '12th award (1988) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1988, 'General Category'),
  ('MANGA', 7699, 'Komikku Shōwa-Shi', 'Kodansha Manga Award', '13th award (1989) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1989, 'General Category'),
  ('MANGA', 62010, 'Gorillaman', 'Kodansha Manga Award', '14th award (1990) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1990, 'General Category'),
  ('MANGA', 101668, 'The Silent Service', 'Kodansha Manga Award', '14th award (1990) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1990, 'General Category'),
  ('MANGA', 11216, 'Kachō Kōsaku Shima', 'Kodansha Manga Award', '15th award (1991) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1991, 'General Category'),
  ('MANGA', 68646, 'Naniwa Kin''yūdō', 'Kodansha Manga Award', '16th award (1992) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1992, 'General Category'),
  ('MANGA', 267, 'Parasyte', 'Kodansha Manga Award', '17th award (1993) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1993, 'General Category'),
  ('MANGA', 58984, 'Hanada Shōnen-shi', 'Kodansha Manga Award', '19th award (1995) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1995, 'General Category'),
  ('MANGA', 28851, 'The Ping Pong Club', 'Kodansha Manga Award', '20th award (1996) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1996, 'General Category'),
  ('MANGA', 1291, 'Dragon Head', 'Kodansha Manga Award', '21st award (1997) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1997, 'General Category'),
  ('MANGA', 1207, 'Gambling Apocalypse: Kaiji', 'Kodansha Manga Award', '22nd award (1998) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1998, 'General Category'),
  ('MANGA', 26450, 'Sōten Kōro', 'Kodansha Manga Award', '22nd award (1998) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1998, 'General Category'),
  ('MANGA', 8324, 'Wangan Midnight', 'Kodansha Manga Award', '23rd award (1999) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 1999, 'General Category'),
  ('MANGA', 14, 'Vagabond', 'Kodansha Manga Award', '24th award (2000) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2000, 'General Category'),
  ('MANGA', 30, '20th Century Boys', 'Kodansha Manga Award', '25th award (2001) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2001, 'General Category'),
  ('MANGA', 8810, 'Zipang', 'Kodansha Manga Award', '26th award (2002) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2002, 'General Category'),
  ('MANGA', 70790, 'Tensai Yanagisawa Kyōju no Seikatsu', 'Kodansha Manga Award', '27th award (2003) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2003, 'General Category'),
  ('MANGA', 3260, 'Basilisk: The Kouga Ninja Scrolls', 'Kodansha Manga Award', '28th award (2004) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2004, 'General Category'),
  ('MANGA', 57545, 'Dragon Zakura', 'Kodansha Manga Award', '29th award (2005) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2005, 'General Category'),
  ('MANGA', 300, 'Mushishi', 'Kodansha Manga Award', '30th award (2006) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2006, 'General Category'),
  ('MANGA', 4572, 'Big Windup!', 'Kodansha Manga Award', '31st award (2007) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2007, 'General Category'),
  ('MANGA', 6948, 'Moyashimon', 'Kodansha Manga Award', '32nd award (2008) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2008, 'General Category'),
  ('MANGA', 2643, 'Oh My Goddess!', 'Kodansha Manga Award', '33rd award (2009) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2009, 'General Category'),
  ('MANGA', 2428, 'Giant Killing', 'Kodansha Manga Award', '34th award (2010) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2010, 'General Category'),
  ('MANGA', 253, 'March Comes In like a Lion', 'Kodansha Manga Award', '35th award (2011) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2011, 'General Category'),
  ('MANGA', 871, 'Space Brothers', 'Kodansha Manga Award', '35th award (2011) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2011, 'General Category'),
  ('MANGA', 16, 'Vinland Saga', 'Kodansha Manga Award', '36th award (2012) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2012, 'General Category'),
  ('MANGA', 68863, 'Gurazeni', 'Kodansha Manga Award', '37th award (2013) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2013, 'General Category')
on conflict (media_type, media_id, source, category) do nothing;

insert into public.canon_seed (media_type, media_id, title, source, source_detail, year, category) values
  ('MANGA', 216, 'Prison School', 'Kodansha Manga Award', '37th award (2013) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2013, 'General Category'),
  ('MANGA', 2405, 'Showa Genroku Rakugo Shinju', 'Kodansha Manga Award', '38th award (2014) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2014, 'General Category'),
  ('MANGA', 997, 'Knights of Sidonia', 'Kodansha Manga Award', '39th award (2015) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2015, 'General Category'),
  ('MANGA', 8965, 'Kōnodori', 'Kodansha Manga Award', '40th award (2016) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2016, 'General Category'),
  ('MANGA', 297, 'The Fable', 'Kodansha Manga Award', '41st award (2017) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2017, 'General Category'),
  ('MANGA', 27094, 'Fragile', 'Kodansha Manga Award', '42nd award (2018) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2018, 'General Category'),
  ('MANGA', 13311, 'Sanju Mariko', 'Kodansha Manga Award', '42nd award (2018) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2018, 'General Category'),
  ('MANGA', 4670, 'What Did You Eat Yesterday?', 'Kodansha Manga Award', '43rd award (2019) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2019, 'General Category'),
  ('MANGA', 93, 'Blue Period', 'Kodansha Manga Award', '44th award (2020) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2020, 'General Category'),
  ('MANGA', 9790, 'Yuria-sensei no Akai Ito', 'Kodansha Manga Award', '45th award (2021) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2021, 'General Category'),
  ('MANGA', 10509, 'Police in a Pod', 'Kodansha Manga Award', '46th award (2022) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2022, 'General Category'),
  ('MANGA', 277, 'Skip and Loafer', 'Kodansha Manga Award', '47th award (2023) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2023, 'General Category'),
  ('MANGA', 1098, 'Medalist', 'Kodansha Manga Award', '48th award (2024) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2024, 'General Category'),
  ('MANGA', 1238, 'Historié', 'Kodansha Manga Award', '49th award (2025) · https://en.wikipedia.org/wiki/Kodansha_Manga_Award', 2025, 'General Category'),
  ('MANGA', 1423, 'Honey and Clover', 'Kono Manga ga Sugoi!', '2006 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2006, '#1 — Female Readers'),
  ('MANGA', 226, 'Kimi ni Todoke', 'Kono Manga ga Sugoi!', '2008 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2008, '#1 — Female Readers'),
  ('MANGA', 1294, 'Kids on the Slope', 'Kono Manga ga Sugoi!', '2009 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2009, '#1 — Female Readers'),
  ('MANGA', 386, 'Chihayafuru', 'Kono Manga ga Sugoi!', '2010 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2010, '#1 — Female Readers'),
  ('MANGA', 13376, 'Her', 'Kono Manga ga Sugoi!', '2011 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2011, '#1 — Female Readers'),
  ('MANGA', 1097, 'My Love Story!!', 'Kono Manga ga Sugoi!', '2013 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2013, '#1 — Female Readers'),
  ('MANGA', 6540, 'Sayonara Sorcier', 'Kono Manga ga Sugoi!', '2014 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2014, '#1 — Female Readers'),
  ('MANGA', 71300, 'Chi-chan wa Chotto Tarinai', 'Kono Manga ga Sugoi!', '2015 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2015, '#1 — Female Readers'),
  ('MANGA', 112, 'Wotakoi: Love Is Hard for Otaku', 'Kono Manga ga Sugoi!', '2016 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2016, '#1 — Female Readers'),
  ('MANGA', 9794, 'Gold Kingdom and Water Kingdom', 'Kono Manga ga Sugoi!', '2017 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2017, '#1 — Female Readers'),
  ('MANGA', 27989, 'Marronnier Ōkoku no Shichinin no Kishi', 'Kono Manga ga Sugoi!', '2018 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2018, '#1 — Female Readers'),
  ('MANGA', 2269, 'BL Metamorphosis', 'Kono Manga ga Sugoi!', '2019 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2019, '#1 — Female Readers'),
  ('MANGA', 7708, 'Not Your Idol', 'Kono Manga ga Sugoi!', '2020 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2020, '#1 — Female Readers'),
  ('MANGA', 4406, 'Onna no Sono no Hoshi', 'Kono Manga ga Sugoi!', '2021 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2021, '#1 — Female Readers'),
  ('MANGA', 2293, 'Credits Roll Into the Sea', 'Kono Manga ga Sugoi!', '2022 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2022, '#1 — Female Readers'),
  ('MANGA', 6697, 'A Witch''s Life in Mongol', 'Kono Manga ga Sugoi!', '2023 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2023, '#1 — Female Readers'),
  ('MANGA', 59912, 'Umibe no Stove: Ōshiro Kogani Tanpenshū', 'Kono Manga ga Sugoi!', '2024 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2024, '#1 — Female Readers'),
  ('MANGA', 91547, 'Tamaki & Amane', 'Kono Manga ga Sugoi!', '2025 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2025, '#1 — Female Readers'),
  ('MANGA', 26444, 'Half Is More', 'Kono Manga ga Sugoi!', '2026 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2026, '#1 — Female Readers'),
  ('MANGA', 149, 'Pluto', 'Kono Manga ga Sugoi!', '2006 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2006, '#1 — Male Readers'),
  ('MANGA', 3767, 'Detroit Metal City', 'Kono Manga ga Sugoi!', '2007 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2007, '#1 — Male Readers'),
  ('MANGA', 11446, '81diver', 'Kono Manga ga Sugoi!', '2008 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2008, '#1 — Male Readers'),
  ('MANGA', 1541, 'Saint Young Men', 'Kono Manga ga Sugoi!', '2009 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2009, '#1 — Male Readers'),
  ('MANGA', 176, 'Bakuman', 'Kono Manga ga Sugoi!', '2010 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2010, '#1 — Male Readers'),
  ('MANGA', 6, 'Attack on Titan', 'Kono Manga ga Sugoi!', '2011 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2011, '#1 — Male Readers'),
  ('MANGA', 829, 'Terra Formars', 'Kono Manga ga Sugoi!', '2013 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2013, '#1 — Male Readers'),
  ('MANGA', 139, 'Assassination Classroom', 'Kono Manga ga Sugoi!', '2014 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2014, '#1 — Male Readers'),
  ('MANGA', 83, 'A Silent Voice', 'Kono Manga ga Sugoi!', '2015 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2015, '#1 — Male Readers'),
  ('MANGA', 151, 'Delicious in Dungeon', 'Kono Manga ga Sugoi!', '2016 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2016, '#1 — Male Readers'),
  ('MANGA', 25912, 'Mr. Tonegawa: Middle Management Blues', 'Kono Manga ga Sugoi!', '2017 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2017, '#1 — Male Readers'),
  ('MANGA', 15, 'The Promised Neverland', 'Kono Manga ga Sugoi!', '2018 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2018, '#1 — Male Readers'),
  ('MANGA', 345, 'Heavenly Delusion', 'Kono Manga ga Sugoi!', '2019 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2019, '#1 — Male Readers'),
  ('MANGA', 13, 'Spy × Family', 'Kono Manga ga Sugoi!', '2020 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2020, '#1 — Male Readers'),
  ('MANGA', 2, 'Chainsaw Man', 'Kono Manga ga Sugoi!', '2021 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2021, '#1 — Male Readers'),
  ('MANGA', 123, 'Look Back', 'Kono Manga ga Sugoi!', '2022 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2022, '#1 — Male Readers'),
  ('MANGA', 225, 'The Summer Hikaru Died', 'Kono Manga ga Sugoi!', '2023 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2023, '#1 — Male Readers'),
  ('MANGA', 10023, 'The Days of Diamond', 'Kono Manga ga Sugoi!', '2024 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2024, '#1 — Male Readers'),
  ('MANGA', 6688, 'Spacewalking with You', 'Kono Manga ga Sugoi!', '2025 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2025, '#1 — Male Readers'),
  ('MANGA', 56607, 'Hon Nara Uru Hodo', 'Kono Manga ga Sugoi!', '2026 edition · https://en.wikipedia.org/wiki/Kono_Manga_ga_Sugoi!', 2026, '#1 — Male Readers'),
  ('MANGA', 10892, 'Gaku: Minna no Yama', 'Manga Taishō', '2008 (1st) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2008, 'Grand Prize'),
  ('MANGA', 386, 'Chihayafuru', 'Manga Taishō', '2009 (2nd) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2009, 'Grand Prize'),
  ('MANGA', 3357, 'Thermae Romae', 'Manga Taishō', '2010 (3rd) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2010, 'Grand Prize'),
  ('MANGA', 253, 'March Comes In like a Lion', 'Manga Taishō', '2011 (4th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2011, 'Grand Prize'),
  ('MANGA', 800, 'Silver Spoon', 'Manga Taishō', '2012 (5th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2012, 'Grand Prize'),
  ('MANGA', 7420, 'Umimachi Diary', 'Manga Taishō', '2013 (6th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2013, 'Grand Prize'),
  ('MANGA', 290, 'A Bride''s Story', 'Manga Taishō', '2014 (7th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2014, 'Grand Prize'),
  ('MANGA', 862, 'Blank Canvas: My So-Called Artist''s Journey', 'Manga Taishō', '2015 (8th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2015, 'Grand Prize'),
  ('MANGA', 155, 'Golden Kamuy', 'Manga Taishō', '2016 (9th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2016, 'Grand Prize'),
  ('MANGA', 96169, 'Hibiki: Shōsetsuka ni Naru Hōhō', 'Manga Taishō', '2017 (10th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2017, 'Grand Prize'),
  ('MANGA', 157, 'Beastars', 'Manga Taishō', '2018 (11th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2018, 'Grand Prize'),
  ('MANGA', 1230, 'Astra Lost in Space', 'Manga Taishō', '2019 (12th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2019, 'Grand Prize'),
  ('MANGA', 93, 'Blue Period', 'Manga Taishō', '2020 (13th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2020, 'Grand Prize'),
  ('MANGA', 89, 'Frieren: Beyond Journey''s End', 'Manga Taishō', '2021 (14th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2021, 'Grand Prize'),
  ('MANGA', 4391, 'The Darwin Incident', 'Manga Taishō', '2022 (15th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2022, 'Grand Prize'),
  ('MANGA', 13659, 'Draw This, Then Die!', 'Manga Taishō', '2023 (16th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2023, 'Grand Prize'),
  ('MANGA', 6688, 'Spacewalking with You', 'Manga Taishō', '2024 (17th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2024, 'Grand Prize'),
  ('MANGA', 49720, 'Alice, Doko Made mo', 'Manga Taishō', '2025 (18th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2025, 'Grand Prize'),
  ('MANGA', 56607, 'Hon Nara Uru Hodo', 'Manga Taishō', '2026 (19th) · https://en.wikipedia.org/wiki/Manga_Taish%C5%8D', 2026, 'Grand Prize'),
  ('MANGA', 18064, 'Golgo 13', 'Shogakukan Manga Award', '21st award (1975) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1975, 'General Category'),
  ('MANGA', 62655, 'Abu-san', 'Shogakukan Manga Award', '22nd award (1976) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1976, 'General Category'),
  ('MANGA', 69706, 'Jarinko Chie', 'Shogakukan Manga Award', '26th award (1980) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1980, 'General Category'),
  ('MANGA', 11135, 'Hidamari no Ki', 'Shogakukan Manga Award', '29th award (1983) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1983, 'General Category'),
  ('MANGA', 65428, 'Human Crossing', 'Shogakukan Manga Award', '30th award (1984) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1984, 'General Category'),
  ('MANGA', 10359, 'Oishinbo', 'Shogakukan Manga Award', '32nd award (1986) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1986, 'General Category'),
  ('MANGA', 1589, 'Hotel', 'Shogakukan Manga Award', '33rd award (1987) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1987, 'General Category'),
  ('MANGA', 3610, 'Yawara!', 'Shogakukan Manga Award', '35th award (1989) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1989, 'General Category'),
  ('MANGA', 10159, 'F', 'Shogakukan Manga Award', '36th award (1990) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1990, 'General Category'),
  ('MANGA', 29507, 'Miyamoto kara Kimi e', 'Shogakukan Manga Award', '38th award (1992) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1992, 'General Category'),
  ('MANGA', 27765, 'Okami-san', 'Shogakukan Manga Award', '38th award (1992) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1992, 'General Category'),
  ('MANGA', 4443, 'Bokkō', 'Shogakukan Manga Award', '40th award (1994) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1994, 'General Category'),
  ('MANGA', 61177, 'Gallery Fake', 'Shogakukan Manga Award', '41st award (1995) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1995, 'General Category'),
  ('MANGA', 64404, 'Ron', 'Shogakukan Manga Award', '41st award (1995) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1995, 'General Category'),
  ('MANGA', 102031, 'Gekka no Kishi', 'Shogakukan Manga Award', '42nd award (1996) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1996, 'General Category'),
  ('MANGA', 4934, 'Azumi', 'Shogakukan Manga Award', '43rd award (1997) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 1997, 'General Category'),
  ('MANGA', 29, 'Monster', 'Shogakukan Manga Award', '46th award (2000) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2000, 'General Category'),
  ('MANGA', 6888, 'Heat', 'Shogakukan Manga Award', '47th award (2001) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2001, 'General Category'),
  ('MANGA', 30, '20th Century Boys', 'Shogakukan Manga Award', '48th award (2002) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2002, 'General Category'),
  ('MANGA', 9897, 'Dr. Kotō Shinryōjo', 'Shogakukan Manga Award', '49th award (2003) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2003, 'General Category'),
  ('MANGA', 3231, 'Team Medical Dragon', 'Shogakukan Manga Award', '50th award (2004) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2004, 'General Category'),
  ('MANGA', 28766, 'A Spirit of the Sun', 'Shogakukan Manga Award', '51st award (2005) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2005, 'General Category'),
  ('MANGA', 802, 'Rainbow - Nisha Rokubō no Shichinin', 'Shogakukan Manga Award', '51st award (2005) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2005, 'General Category'),
  ('MANGA', 34699, 'Bambino!', 'Shogakukan Manga Award', '53rd award (2007) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2007, 'General Category'),
  ('MANGA', 6534, 'Kurosagi', 'Shogakukan Manga Award', '53rd award (2007) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2007, 'General Category'),
  ('MANGA', 10892, 'Gaku: Minna no Yama', 'Shogakukan Manga Award', '54th award (2008) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2008, 'General Category'),
  ('MANGA', 7827, 'Shin''ya Shokudō', 'Shogakukan Manga Award', '55th award (2009) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2009, 'General Category'),
  ('MANGA', 871, 'Space Brothers', 'Shogakukan Manga Award', '56th award (2010) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2010, 'General Category')
on conflict (media_type, media_id, source, category) do nothing;

insert into public.canon_seed (media_type, media_id, title, source, source_detail, year, category) values
  ('MANGA', 3600, 'Ushijima the Loan Shark', 'Shogakukan Manga Award', '56th award (2010) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2010, 'General Category'),
  ('MANGA', 1294, 'Kids on the Slope', 'Shogakukan Manga Award', '57th award (2011) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2011, 'General Category'),
  ('MANGA', 192, 'I Am a Hero', 'Shogakukan Manga Award', '58th award (2012) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2012, 'General Category'),
  ('MANGA', 66860, 'Mogura no Uta', 'Shogakukan Manga Award', '59th award (2013) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2013, 'General Category'),
  ('MANGA', 11883, 'Aoi Honō', 'Shogakukan Manga Award', '60th award (2014) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2014, 'General Category'),
  ('MANGA', 10705, 'Asahinagu', 'Shogakukan Manga Award', '60th award (2014) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2014, 'General Category'),
  ('MANGA', 894, 'Sunny', 'Shogakukan Manga Award', '61st award (2015) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2015, 'General Category'),
  ('MANGA', 7420, 'Umimachi Diary', 'Shogakukan Manga Award', '61st award (2015) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2015, 'General Category'),
  ('MANGA', 884, 'Blue Giant', 'Shogakukan Manga Award', '62nd award (2016) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2016, 'General Category'),
  ('MANGA', 711, 'After the Rain', 'Shogakukan Manga Award', '63rd award (2017) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2017, 'General Category'),
  ('MANGA', 101190, 'Kūbo Ibuki', 'Shogakukan Manga Award', '63rd award (2017) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2017, 'General Category'),
  ('MANGA', 96169, 'Hibiki: Shōsetsuka ni Naru Hōhō', 'Shogakukan Manga Award', '64th award (2018) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2018, 'General Category'),
  ('MANGA', 68502, 'Kenkō de Bunkateki na Saitei Gendo no Seikatsu', 'Shogakukan Manga Award', '64th award (2018) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2018, 'General Category'),
  ('MANGA', 366, 'Aoashi', 'Shogakukan Manga Award', '65th award (2019) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2019, 'General Category'),
  ('MANGA', 20, 'Kaguya-sama: Love is War', 'Shogakukan Manga Award', '65th award (2019) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2019, 'General Category'),
  ('MANGA', 199, 'Dead Dead Demon''s Dededede Destruction', 'Shogakukan Manga Award', '66th award (2020) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2020, 'General Category'),
  ('MANGA', 10509, 'Police in a Pod', 'Shogakukan Manga Award', '66th award (2020) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2020, 'General Category'),
  ('MANGA', 1907, 'Don''t Call It Mystery', 'Shogakukan Manga Award', '67th award (2021) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2021, 'General Category'),
  ('MANGA', 1098, 'Medalist', 'Shogakukan Manga Award', '68th award (2022) · https://en.wikipedia.org/wiki/Shogakukan_Manga_Award', 2022, 'General Category'),
  ('MANGA', 3003, 'Doraemon', 'Tezuka Cultural Prize', '1st prize (1997) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 1997, 'Grand Prize'),
  ('MANGA', 31319, 'Bocchan No Jidai', 'Tezuka Cultural Prize', '2nd prize (1998) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 1998, 'Grand Prize'),
  ('MANGA', 29, 'Monster', 'Tezuka Cultural Prize', '3rd prize (1999) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 1999, 'Grand Prize'),
  ('MANGA', 31147, 'Onmyōji', 'Tezuka Cultural Prize', '5th prize (2001) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2001, 'Grand Prize'),
  ('MANGA', 14, 'Vagabond', 'Tezuka Cultural Prize', '6th prize (2002) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2002, 'Grand Prize'),
  ('MANGA', 27776, 'The Yellow Book: A Friend Named Jacques Thibault', 'Tezuka Cultural Prize', '7th prize (2003) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2003, 'Grand Prize'),
  ('MANGA', 1088, 'Helter Skelter', 'Tezuka Cultural Prize', '8th prize (2004) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2004, 'Grand Prize'),
  ('MANGA', 149, 'Pluto', 'Tezuka Cultural Prize', '9th prize (2005) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2005, 'Grand Prize'),
  ('MANGA', 7879, 'Disappearance Diary', 'Tezuka Cultural Prize', '10th prize (2006) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2006, 'Grand Prize'),
  ('MANGA', 6948, 'Moyashimon', 'Tezuka Cultural Prize', '12th prize (2008) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2008, 'Grand Prize'),
  ('MANGA', 3627, 'A Drifting Life', 'Tezuka Cultural Prize', '13th prize (2009) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2009, 'Grand Prize'),
  ('MANGA', 2024, 'Ōoku: The Inner Chambers', 'Tezuka Cultural Prize', '13th prize (2009) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2009, 'Grand Prize'),
  ('MANGA', 6469, 'Hyouge Mono', 'Tezuka Cultural Prize', '14th prize (2010) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2010, 'Grand Prize'),
  ('MANGA', 4659, 'Jin', 'Tezuka Cultural Prize', '15th prize (2011) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2011, 'Grand Prize'),
  ('MANGA', 1568, 'Takemitsuzamurai', 'Tezuka Cultural Prize', '15th prize (2011) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2011, 'Grand Prize'),
  ('MANGA', 1238, 'Historié', 'Tezuka Cultural Prize', '16th prize (2012) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2012, 'Grand Prize'),
  ('MANGA', 97, 'Kingdom', 'Tezuka Cultural Prize', '17th prize (2013) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2013, 'Grand Prize'),
  ('MANGA', 253, 'March Comes in Like a Lion', 'Tezuka Cultural Prize', '18th prize (2014) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2014, 'Grand Prize'),
  ('MANGA', 117, 'Yotsuba&!', 'Tezuka Cultural Prize', '20th prize (2016) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2016, 'Grand Prize'),
  ('MANGA', 58910, 'Hana ni Somu', 'Tezuka Cultural Prize', '21st prize (2017) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2017, 'Grand Prize'),
  ('MANGA', 155, 'Golden Kamuy', 'Tezuka Cultural Prize', '22nd prize (2018) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2018, 'Grand Prize'),
  ('MANGA', 13187, 'Jitterbug The Forties', 'Tezuka Cultural Prize', '23rd prize (2019) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2019, 'Grand Prize'),
  ('MANGA', 13668, 'Nyx no Lantern', 'Tezuka Cultural Prize', '24th prize (2020) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2020, 'Grand Prize'),
  ('MANGA', 8326, 'Land', 'Tezuka Cultural Prize', '25th prize (2021) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2021, 'Grand Prize'),
  ('MANGA', 1447, 'Orb: On the Movements of the Earth', 'Tezuka Cultural Prize', '26th prize (2022) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2022, 'Grand Prize'),
  ('MANGA', 9790, 'Yuria-sensei no Akai Ito', 'Tezuka Cultural Prize', '27th prize (2023) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2023, 'Grand Prize'),
  ('MANGA', 12932, 'PLINIVS', 'Tezuka Cultural Prize', '28th prize (2024) · https://en.wikipedia.org/wiki/Tezuka_Osamu_Cultural_Prize', 2024, 'Grand Prize'),
  ('ANIME', 111, 'Spirited Away', 'Tokyo Anime Award', 'Tokyo Anime Award 2002 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2002, 'Grand Prix'),
  ('ANIME', 2345, 'Mobile Suit Gundam Seed', 'Tokyo Anime Award', 'Tokyo Anime Award 2004 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2004, 'Grand Prix'),
  ('ANIME', 161, 'Howl''s Moving Castle', 'Tokyo Anime Award', 'Tokyo Anime Award 2005 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2005, 'Grand Prix'),
  ('ANIME', 1488, 'Fullmetal Alchemist the Movie: Conqueror of Shamballa', 'Tokyo Anime Award', 'Tokyo Anime Award 2006 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2006, 'Grand Prix'),
  ('ANIME', 390, 'The Girl Who Leapt Through Time', 'Tokyo Anime Award', 'Tokyo Anime Award 2007 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2007, 'Grand Prix'),
  ('ANIME', 502, 'Evangelion: 1.0 You Are (Not) Alone', 'Tokyo Anime Award', 'Tokyo Anime Award 2008 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2008, 'Grand Prix'),
  ('ANIME', 374, 'Ponyo', 'Tokyo Anime Award', 'Tokyo Anime Award 2009 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2009, 'Grand Prix'),
  ('ANIME', 798, 'Summer Wars', 'Tokyo Anime Award', 'Tokyo Anime Award 2010 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2010, 'Grand Prix'),
  ('ANIME', 858, 'The Secret World of Arrietty', 'Tokyo Anime Award', 'Tokyo Anime Award 2011 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2011, 'Grand Prix'),
  ('ANIME', 1349, 'From Up on Poppy Hill', 'Tokyo Anime Award', 'Tokyo Anime Award 2012 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2012, 'Grand Prix'),
  ('ANIME', 334, 'Wolf Children', 'Tokyo Anime Award', 'Tokyo Anime Award 2013 Grand Prix · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2013, 'Grand Prix'),
  ('ANIME', 1338, 'Millennium Actress', 'Tokyo Anime Award', 'Tokyo Anime Award 2003 Grand Prix (Best Entry Award, Feature Film — de facto Grand Prix; no Animation of the Year awarded in 2003) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2003, 'Grand Prix (Film)'),
  ('ANIME', 841, 'The Wind Rises', 'Tokyo Anime Award', 'Tokyo Anime Award 2014 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2014, 'Grand Prix (Film)'),
  ('ANIME', 1856, 'Love Live! The School Idol Movie', 'Tokyo Anime Award', 'Tokyo Anime Award 2016 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2016, 'Grand Prix (Film)'),
  ('ANIME', 16, 'A Silent Voice', 'Tokyo Anime Award', 'Tokyo Anime Award 2017 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2017, 'Grand Prix (Film)'),
  ('ANIME', 1327, 'In This Corner of the World', 'Tokyo Anime Award', 'Tokyo Anime Award 2018 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2018, 'Grand Prix (Film)'),
  ('ANIME', 4413, 'Detective Conan: Zero the Enforcer', 'Tokyo Anime Award', 'Tokyo Anime Award 2019 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2019, 'Grand Prix (Film)'),
  ('ANIME', 166, 'Weathering with You', 'Tokyo Anime Award', 'Tokyo Anime Award 2020 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2020, 'Grand Prix (Film)'),
  ('ANIME', 345, 'Violet Evergarden: The Movie', 'Tokyo Anime Award', 'Tokyo Anime Award 2021 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2021, 'Grand Prix (Film)'),
  ('ANIME', 810, 'Evangelion: 3.0+1.0 Thrice Upon a Time', 'Tokyo Anime Award', 'Tokyo Anime Award 2022 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2022, 'Grand Prix (Film)'),
  ('ANIME', 1201, 'One Piece Film: Red', 'Tokyo Anime Award', 'Tokyo Anime Award 2023 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2023, 'Grand Prix (Film)'),
  ('ANIME', 12908, 'The First Slam Dunk', 'Tokyo Anime Award', 'Tokyo Anime Award 2024 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2024, 'Grand Prix (Film)'),
  ('ANIME', 945, 'Look Back', 'Tokyo Anime Award', 'Tokyo Anime Award 2025 Grand Prix (Anime of the Year, Feature Film) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2025, 'Grand Prix (Film)'),
  ('ANIME', 555, 'Demon Slayer: Kimetsu no Yaiba – The Movie: Infinity Castle – Part 1: Akaza Returns', 'Tokyo Anime Award', 'Tokyo Anime Award 2026 Grand Prix (Anime of the Year, Feature Film) · https://animehunch.com/demon-slayer-infinity-castle-gundam-gquuuuuux-taaf-2026/', 2026, 'Grand Prix (Film)'),
  ('ANIME', 5638, 'Sentō Yōsei Yukikaze', 'Tokyo Anime Award', 'Tokyo Anime Award 2003 Grand Prix (Best Entry Award, OVA — de facto Grand Prix; no Animation of the Year awarded in 2003) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2003, 'Grand Prix (OVA)'),
  ('ANIME', 5761, 'Hanada Shōnen-shi', 'Tokyo Anime Award', 'Tokyo Anime Award 2003 Grand Prix (Best Entry Award, Television — de facto Grand Prix; no Animation of the Year awarded in 2003) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2003, 'Grand Prix (TV)'),
  ('ANIME', 2, 'Attack on Titan', 'Tokyo Anime Award', 'Tokyo Anime Award 2014 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2014, 'Grand Prix (TV)'),
  ('ANIME', 758, 'Ping Pong the Animation', 'Tokyo Anime Award', 'Tokyo Anime Award 2015 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2015, 'Grand Prix (TV)'),
  ('ANIME', 799, 'Shirobako', 'Tokyo Anime Award', 'Tokyo Anime Award 2016 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2016, 'Grand Prix (TV)'),
  ('ANIME', 282, 'Yuri!!! on Ice', 'Tokyo Anime Award', 'Tokyo Anime Award 2017 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2017, 'Grand Prix (TV)'),
  ('ANIME', 73486, 'Kemono Friends', 'Tokyo Anime Award', 'Tokyo Anime Award 2018 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2018, 'Grand Prix (TV)'),
  ('ANIME', 450, 'Zombie Land Saga', 'Tokyo Anime Award', 'Tokyo Anime Award 2019 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2019, 'Grand Prix (TV)'),
  ('ANIME', 3, 'Demon Slayer: Kimetsu no Yaiba', 'Tokyo Anime Award', 'Tokyo Anime Award 2020 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2020, 'Grand Prix (TV)'),
  ('ANIME', 784, 'Keep Your Hands Off Eizouken!', 'Tokyo Anime Award', 'Tokyo Anime Award 2021 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2021, 'Grand Prix (TV)'),
  ('ANIME', 5, 'Jujutsu Kaisen', 'Tokyo Anime Award', 'Tokyo Anime Award 2022 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2022, 'Grand Prix (TV)'),
  ('ANIME', 97, 'Spy × Family', 'Tokyo Anime Award', 'Tokyo Anime Award 2023 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2023, 'Grand Prix (TV)'),
  ('ANIME', 195, 'Oshi no Ko', 'Tokyo Anime Award', 'Tokyo Anime Award 2024 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2024, 'Grand Prix (TV)'),
  ('ANIME', 145, 'Frieren: Beyond Journey''s End', 'Tokyo Anime Award', 'Tokyo Anime Award 2025 Grand Prix (Anime of the Year, TV Series) · https://en.wikipedia.org/wiki/Tokyo_Anime_Award', 2025, 'Grand Prix (TV)'),
  ('ANIME', 2330, 'Mobile Suit Gundam GQuuuuuuX', 'Tokyo Anime Award', 'Tokyo Anime Award 2026 Grand Prix (Anime of the Year, TV Series) · https://animehunch.com/demon-slayer-infinity-castle-gundam-gquuuuuux-taaf-2026/', 2026, 'Grand Prix (TV)'),
  ('ANIME', 297, 'Akira', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 6171, 'Astro Boy', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 2, 'Attack on Titan', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 412, 'Berserk', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 892, 'Cardcaptor Sakura', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 203, 'Clannad', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 109, 'Code Geass', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 117, 'Cowboy Bebop', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 4, 'Death Note', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 295, 'Dragon Ball', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 318, 'FLCL', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 163, 'Fate/Zero', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 12, 'Fullmetal Alchemist: Brotherhood', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 419, 'Ghost in the Shell', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 207, 'Gintama', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon')
on conflict (media_type, media_id, source, category) do nothing;

insert into public.canon_seed (media_type, media_id, title, source, source_detail, year, category) values
  ('ANIME', 720, 'Hunter x Hunter', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 1789, 'JoJo''s Bizarre Adventure', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 220, 'K-On!', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 133, 'Kill la Kill', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 1072, 'Legend of the Galactic Heroes', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 2284, 'Lupin III', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 2349, 'Macross', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 1746, 'Mobile Suit Gundam', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 181, 'Monster', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 221, 'My Neighbor Totoro', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 14, 'Naruto', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 110, 'Neon Genesis Evangelion', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 11, 'One Piece', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 8, 'One Punch Man', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 286, 'Perfect Blue', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 500, 'Pokémon', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 200, 'Princess Mononoke', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 180, 'Puella Magi Madoka Magica', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 1131, 'Revolutionary Girl Utena', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 869, 'Sailor Moon', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 222, 'Samurai Champloo', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 269, 'Serial Experiments Lain', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 373, 'Spice & Wolf', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 111, 'Spirited Away', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 29, 'Steins;Gate', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 13, 'Sword Art Online', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 155, 'Tengen Toppa Gurren Lagann', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 325, 'The Melancholy of Haruhi Suzumiya', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 168, 'The Monogatari Series', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 2045, 'Tomorrow''s Joe', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 96, 'Toradora!', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 429, 'Trigun', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 23, 'Your Lie in April', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 15, 'Your Name', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon'),
  ('ANIME', 447, 'Yu Yu Hakusho', 'r/anime Classics', 'r/anime ''Classics of Anime'' Poll (2019), Top 50 — linked from r/anime wiki Recommendations · https://i.redd.it/hd24s6gim1n31.png', null, 'Classics Canon')
on conflict (media_type, media_id, source, category) do nothing;
