-- Realm Graph v1 — taxonomy + editorial realm signatures.
-- Spec: docs/superpowers/specs/2026-07-31-realm-graph-master-plan.md (§2 taxonomy,
-- §3 realm_signatures role). 40 realms in 10 families + 2 manga-native realms.
--
-- realm_meta:        catalog-level editorial data (display copy), public read.
-- realm_signatures:  realm -> {tag_key: weight}; hand-drafted, swarm-refined,
--                    owner-vetoed. Consumed by media_realm_membership (matview):
--                    membership = normalized dot(title IDF tag vector, signature).
--
-- Key conventions (same substrate as 20260731060000_taste_math_v2.sql):
--   tag_key = lower(tags.name); genre pseudo-keys = 'genre:' || lower(genre),
--   genres drawn from anime.genres / manga.genres (19-value AniList set).
--
-- Weight semantics: signatures are OR-weighted bundles (positive weights only —
-- the dot product has no counter-signal support, so every key must PULL the
-- right titles). 1.0 = defining (the realm IS this), 0.7-0.9 = core,
-- 0.4-0.6 = supporting, 0.1-0.3 = weak/context. Distinctive (high-IDF) tags
-- are preferred over generic ones; manga-specific tag variants (gekiga,
-- 4-koma, short-form chapter, full color, long strip, demographics) are
-- included where the media vocabularies differ.
--
-- Families (lowercase-hyphenated): epic-adventure, emotional-core, mind-thrill,
-- speculative-worlds, craft-art, laughter, life-world, intense,
-- relationships-identity, otaku-register (surfaced selectively, never
-- editorially promoted), seinen-alternative (manga-native: realms 38-39), young.

begin;

-- ---------------------------------------------------------------------------
-- 1) Tables
-- ---------------------------------------------------------------------------
create table if not exists public.realm_signatures (
  realm text not null,
  family text not null,
  tag_key text not null,
  weight real not null check (weight between 0 and 1),
  primary key (realm, tag_key)
);

create table if not exists public.realm_meta (
  realm text primary key,
  family text not null,
  display_name text not null,
  blurb text not null,
  sort int not null
);

-- ---------------------------------------------------------------------------
-- 2) RLS — catalog-level editorial data, no user data: public SELECT.
-- ---------------------------------------------------------------------------
alter table public.realm_signatures enable row level security;
alter table public.realm_meta enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='realm_signatures' and policyname='realm_signatures_select_all'
  ) then
    create policy realm_signatures_select_all on public.realm_signatures
      for select using (true);
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='realm_meta' and policyname='realm_meta_select_all'
  ) then
    create policy realm_meta_select_all on public.realm_meta
      for select using (true);
  end if;
end $$;

grant select on public.realm_signatures to anon, authenticated;
grant select on public.realm_meta to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3) Seed realm_meta (40 realms, spec §2 order = sort)
-- ---------------------------------------------------------------------------
insert into public.realm_meta (realm, family, display_name, blurb, sort) values
  ('grand-adventure', 'epic-adventure', 'Grand Adventure', 'Journeys and quests with mythic scope — the road is the point (Frieren, One Piece).', 1),
  ('battle-shounen', 'epic-adventure', 'Battle Shounen', 'Power systems, tournaments, rivals — strength earned in public (Naruto, Jujutsu Kaisen, My Hero Academia).', 2),
  ('dark-fantasy', 'epic-adventure', 'Dark Fantasy', 'Beautiful and brutal at once — wonder with teeth (Berserk, Claymore, Attack on Titan).', 3),
  ('isekai-reincarnation', 'epic-adventure', 'Isekai & Reincarnation', 'Other worlds, all tiers — from Re:Zero to vending machines.', 4),
  ('sword-samurai', 'epic-adventure', 'Sword & Samurai', 'Blade craft, honor, history-adjacent (Vagabond, Rurouni Kenshin).', 5),
  ('historical-epic', 'epic-adventure', 'Historical Epic', 'Real eras, grand scale (Vinland Saga, Kingdom, Golden Kamuy).', 6),
  ('quiet-melancholy', 'emotional-core', 'Quiet Melancholy', 'Gentle sadness, time and loss (Mushishi, Violet Evergarden).', 7),
  ('romance-slow-burn', 'emotional-core', 'Romance & Slow Burn', 'Longing done seriously (Your Lie in April, Fruits Basket).', 8),
  ('slice-of-life-iyashikei', 'emotional-core', 'Slice of Life & Iyashikei', 'Healing, ordinary days (Yuru Camp, Barakamon, Aria).', 9),
  ('coming-of-age', 'emotional-core', 'Coming of Age', 'Growing up as the subject (Spirited Away, March Comes in Like a Lion).', 10),
  ('tragedy-tearjerker', 'emotional-core', 'Tragedy & Tearjerker', 'Engineered devastation (Grave of the Fireflies, Clannad After Story).', 11),
  ('psychological-thriller', 'mind-thrill', 'Psychological Thriller', 'Cat-and-mouse minds (Death Note, Monster, Psycho-Pass).', 12),
  ('mystery-detective', 'mind-thrill', 'Mystery & Detective', 'Puzzles and procedures (Erased, Hyouka, Detective Conan).', 13),
  ('horror-dread', 'mind-thrill', 'Horror & Dread', 'Fear as craft (Another, Higurashi, Junji Ito).', 14),
  ('mind-game-strategy', 'mind-thrill', 'Mind Game & Strategy', 'Rules, gambits, debts (Kaiji, Akagi, Death Parade).', 15),
  ('sci-fi-space', 'speculative-worlds', 'Sci-Fi & Space', 'Futures, frontiers, engineering (Cowboy Bebop, Legend of the Galactic Heroes, Planetes).', 16),
  ('mecha', 'speculative-worlds', 'Mecha', 'Machines and their pilots (Gundam, Evangelion, Code Geass).', 17),
  ('cyberpunk-dystopia', 'speculative-worlds', 'Cyberpunk & Dystopia', 'Systems eating people (Akira, Ghost in the Shell, Psycho-Pass).', 18),
  ('time-parallel-worlds', 'speculative-worlds', 'Time & Parallel Worlds', 'Loops, leaps, branches (Steins;Gate, Re:Zero, Summertime Rendering).', 19),
  ('auteur-cinema', 'craft-art', 'Auteur Cinema', 'The legendary film realm — directors as the signature (Ghibli, Kon, Shinkai, Hosoda, Yuasa).', 20),
  ('arthouse-experimental', 'craft-art', 'Arthouse & Experimental', 'Form as content (Kaiba, Tatami Galaxy, Ping Pong).', 21),
  ('classic-serial-canon', 'craft-art', 'Classic Serial Canon', 'The long-form legends (Fullmetal Alchemist: Brotherhood, Legend of the Galactic Heroes).', 22),
  ('comedy-parody', 'laughter', 'Comedy & Parody', 'Jokes as the engine (Gintama, Konosuba, Nichijou).', 23),
  ('romantic-comedy', 'laughter', 'Romantic Comedy', 'Love as farce and charm (Kaguya-sama, Toradora, Takagi-san).', 24),
  ('sports-competition', 'life-world', 'Sports & Competition', 'Bodies and brackets (Haikyuu!!, Chihayafuru, Blue Lock).', 25),
  ('music-performance', 'life-world', 'Music & Performance', 'Stages and practice rooms (Nodame Cantabile, Bocchi the Rock!, Your Lie in April).', 26),
  ('food-craft', 'life-world', 'Food & Craft', 'Cuisine and artisans (Food Wars, Delicious in Dungeon, Bartender).', 27),
  ('workplace-adult-life', 'life-world', 'Workplace & Adult Life', 'Jobs, rent, small victories (Shirobako, Aggretsuko, Wotakoi).', 28),
  ('war-military', 'intense', 'War & Military', 'Campaigns and command (86, Saga of Tanya the Evil, Legend of the Galactic Heroes).', 29),
  ('crime-underworld', 'intense', 'Crime & Underworld', 'Gangs, heists, vengeance (Black Lagoon, 91 Days, Banana Fish).', 30),
  ('supernatural-yokai', 'intense', 'Supernatural & Yokai', 'Spirits among us (Natsume''s Book of Friends, Mononoke, Noragami).', 31),
  ('bl-yuri', 'relationships-identity', 'BL & Yuri', 'Queer romance as the subject (Given, Bloom Into You).', 32),
  ('family-generations', 'relationships-identity', 'Family & Generations', 'Parents, children, time (Wolf Children, Sweetness & Lightning).', 33),
  ('idol-showbiz', 'relationships-identity', 'Idol & Showbiz', 'Fame''s machinery (Oshi no Ko, Idolmaster).', 34),
  ('moe-cgdct', 'otaku-register', 'Moe & CGDCT', 'Cute girls, cute things (K-On!, Bocchi the Rock!).', 35),
  ('ecchi-fanservice', 'otaku-register', 'Ecchi & Fanservice', 'Self-describing; primarily an avoidance-mapping realm.', 36),
  ('gag-short-form', 'otaku-register', 'Gag & Short-Form', 'Quick-hit comedy — sketches, strips, and shorts.', 37),
  ('seinen-drama', 'seinen-alternative', 'Seinen Drama', 'Adult interiority, no genre net (Oyasumi Punpun, Solanin, March Comes in Like a Lion).', 38),
  ('gekiga-alternative', 'seinen-alternative', 'Gekiga & Alternative', 'The manga-as-art lineage (Tezuka legacy, alternative press).', 39),
  ('kids-family', 'young', 'Kids & Family', 'All-ages wonder (Anpanman, Yokai Watch, Ghibli-adjacent kids'' works).', 40)
on conflict (realm) do update set
  family = excluded.family,
  display_name = excluded.display_name,
  blurb = excluded.blurb,
  sort = excluded.sort;

-- ---------------------------------------------------------------------------
-- 4) Seed realm_signatures (842 rows)
-- ---------------------------------------------------------------------------
insert into public.realm_signatures (realm, family, tag_key, weight) values
  ('grand-adventure', 'epic-adventure', 'genre:adventure', 1),
  ('grand-adventure', 'epic-adventure', 'travel', 0.8),
  ('grand-adventure', 'epic-adventure', 'pirates', 0.7),
  ('grand-adventure', 'epic-adventure', 'mythology', 0.7),
  ('grand-adventure', 'epic-adventure', 'genre:fantasy', 0.6),
  ('grand-adventure', 'epic-adventure', 'ensemble cast', 0.6),
  ('grand-adventure', 'epic-adventure', 'ships', 0.6),
  ('grand-adventure', 'epic-adventure', 'lost civilization', 0.6),
  ('grand-adventure', 'epic-adventure', 'dragons', 0.6),
  ('grand-adventure', 'epic-adventure', 'magic', 0.6),
  ('grand-adventure', 'epic-adventure', 'medieval', 0.5),
  ('grand-adventure', 'epic-adventure', 'wilderness', 0.5),
  ('grand-adventure', 'epic-adventure', 'elf', 0.5),
  ('grand-adventure', 'epic-adventure', 'fairy tale', 0.5),
  ('grand-adventure', 'epic-adventure', 'demons', 0.4),
  ('grand-adventure', 'epic-adventure', 'genre:action', 0.4),
  ('grand-adventure', 'epic-adventure', 'episodic', 0.3),
  ('grand-adventure', 'epic-adventure', 'rescue', 0.3),
  ('grand-adventure', 'epic-adventure', 'male protagonist', 0.3),
  ('grand-adventure', 'epic-adventure', 'shounen', 0.3),
  ('battle-shounen', 'epic-adventure', 'shounen', 1),
  ('battle-shounen', 'epic-adventure', 'super power', 1),
  ('battle-shounen', 'epic-adventure', 'genre:action', 0.8),
  ('battle-shounen', 'epic-adventure', 'curses', 0.7),
  ('battle-shounen', 'epic-adventure', 'martial arts', 0.7),
  ('battle-shounen', 'epic-adventure', 'demons', 0.6),
  ('battle-shounen', 'epic-adventure', 'superhero', 0.6),
  ('battle-shounen', 'epic-adventure', 'ninja', 0.6),
  ('battle-shounen', 'epic-adventure', 'ensemble cast', 0.5),
  ('battle-shounen', 'epic-adventure', 'male protagonist', 0.5),
  ('battle-shounen', 'epic-adventure', 'swordplay', 0.5),
  ('battle-shounen', 'epic-adventure', 'genre:supernatural', 0.5),
  ('battle-shounen', 'epic-adventure', 'school', 0.4),
  ('battle-shounen', 'epic-adventure', 'exorcism', 0.4),
  ('battle-shounen', 'epic-adventure', 'urban fantasy', 0.3),
  ('battle-shounen', 'epic-adventure', 'delinquents', 0.3),
  ('battle-shounen', 'epic-adventure', 'mythology', 0.3),
  ('battle-shounen', 'epic-adventure', 'gods', 0.3),
  ('battle-shounen', 'epic-adventure', 'genre:fantasy', 0.3),
  ('battle-shounen', 'epic-adventure', 'afterlife', 0.2),
  ('dark-fantasy', 'epic-adventure', 'genre:fantasy', 0.9),
  ('dark-fantasy', 'epic-adventure', 'medieval', 0.8),
  ('dark-fantasy', 'epic-adventure', 'gore', 0.8),
  ('dark-fantasy', 'epic-adventure', 'demons', 0.7),
  ('dark-fantasy', 'epic-adventure', 'seinen', 0.7),
  ('dark-fantasy', 'epic-adventure', 'body horror', 0.6),
  ('dark-fantasy', 'epic-adventure', 'tragedy', 0.6),
  ('dark-fantasy', 'epic-adventure', 'survival', 0.5),
  ('dark-fantasy', 'epic-adventure', 'war', 0.5),
  ('dark-fantasy', 'epic-adventure', 'revenge', 0.5),
  ('dark-fantasy', 'epic-adventure', 'swordplay', 0.5),
  ('dark-fantasy', 'epic-adventure', 'anti-hero', 0.5),
  ('dark-fantasy', 'epic-adventure', 'genre:action', 0.5),
  ('dark-fantasy', 'epic-adventure', 'curses', 0.4),
  ('dark-fantasy', 'epic-adventure', 'torture', 0.4),
  ('dark-fantasy', 'epic-adventure', 'cannibalism', 0.4),
  ('dark-fantasy', 'epic-adventure', 'conspiracy', 0.4),
  ('dark-fantasy', 'epic-adventure', 'dystopian', 0.4),
  ('dark-fantasy', 'epic-adventure', 'military', 0.4),
  ('dark-fantasy', 'epic-adventure', 'genre:horror', 0.4),
  ('dark-fantasy', 'epic-adventure', 'female protagonist', 0.3),
  ('dark-fantasy', 'epic-adventure', 'kaiju', 0.3),
  ('dark-fantasy', 'epic-adventure', 'philosophy', 0.3),
  ('isekai-reincarnation', 'epic-adventure', 'isekai', 1),
  ('isekai-reincarnation', 'epic-adventure', 'reincarnation', 1),
  ('isekai-reincarnation', 'epic-adventure', 'reverse isekai', 0.8),
  ('isekai-reincarnation', 'epic-adventure', 'villainess', 0.8),
  ('isekai-reincarnation', 'epic-adventure', 'virtual world', 0.7),
  ('isekai-reincarnation', 'epic-adventure', 'magic', 0.7),
  ('isekai-reincarnation', 'epic-adventure', 'genre:fantasy', 0.7),
  ('isekai-reincarnation', 'epic-adventure', 'video games', 0.6),
  ('isekai-reincarnation', 'epic-adventure', 'medieval', 0.5),
  ('isekai-reincarnation', 'epic-adventure', 'dungeon', 0.5),
  ('isekai-reincarnation', 'epic-adventure', 'female harem', 0.4),
  ('isekai-reincarnation', 'epic-adventure', 'elf', 0.4),
  ('isekai-reincarnation', 'epic-adventure', 'demons', 0.4),
  ('isekai-reincarnation', 'epic-adventure', 'kingdom management', 0.4),
  ('isekai-reincarnation', 'epic-adventure', 'genre:adventure', 0.4),
  ('isekai-reincarnation', 'epic-adventure', 'hikikomori', 0.3),
  ('isekai-reincarnation', 'epic-adventure', 'male protagonist', 0.3),
  ('isekai-reincarnation', 'epic-adventure', 'dragons', 0.3),
  ('isekai-reincarnation', 'epic-adventure', 'genre:comedy', 0.2),
  ('isekai-reincarnation', 'epic-adventure', 'time loop', 0.2),
  ('sword-samurai', 'epic-adventure', 'samurai', 1),
  ('sword-samurai', 'epic-adventure', 'swordplay', 1),
  ('sword-samurai', 'epic-adventure', 'historical', 0.8),
  ('sword-samurai', 'epic-adventure', 'martial arts', 0.6),
  ('sword-samurai', 'epic-adventure', 'seinen', 0.6),
  ('sword-samurai', 'epic-adventure', 'ninja', 0.5),
  ('sword-samurai', 'epic-adventure', 'revenge', 0.5),
  ('sword-samurai', 'epic-adventure', 'genre:action', 0.5),
  ('sword-samurai', 'epic-adventure', 'assassins', 0.4),
  ('sword-samurai', 'epic-adventure', 'war', 0.4),
  ('sword-samurai', 'epic-adventure', 'spearplay', 0.4),
  ('sword-samurai', 'epic-adventure', 'philosophy', 0.4),
  ('sword-samurai', 'epic-adventure', 'archery', 0.3),
  ('sword-samurai', 'epic-adventure', 'politics', 0.3),
  ('sword-samurai', 'epic-adventure', 'tragedy', 0.3),
  ('sword-samurai', 'epic-adventure', 'shounen', 0.3),
  ('sword-samurai', 'epic-adventure', 'gore', 0.3),
  ('sword-samurai', 'epic-adventure', 'genre:drama', 0.3),
  ('historical-epic', 'epic-adventure', 'historical', 1),
  ('historical-epic', 'epic-adventure', 'war', 0.8),
  ('historical-epic', 'epic-adventure', 'politics', 0.7),
  ('historical-epic', 'epic-adventure', 'vikings', 0.7),
  ('historical-epic', 'epic-adventure', 'ancient china', 0.7),
  ('historical-epic', 'epic-adventure', 'military', 0.7),
  ('historical-epic', 'epic-adventure', 'seinen', 0.6),
  ('historical-epic', 'epic-adventure', 'kingdom management', 0.5),
  ('historical-epic', 'epic-adventure', 'royal affairs', 0.5),
  ('historical-epic', 'epic-adventure', 'indigenous cultures', 0.5),
  ('historical-epic', 'epic-adventure', 'medieval', 0.5),
  ('historical-epic', 'epic-adventure', 'survival', 0.4),
  ('historical-epic', 'epic-adventure', 'revenge', 0.4),
  ('historical-epic', 'epic-adventure', 'biographical', 0.4),
  ('historical-epic', 'epic-adventure', 'genre:action', 0.4),
  ('historical-epic', 'epic-adventure', 'genre:drama', 0.4),
  ('historical-epic', 'epic-adventure', 'religion', 0.3),
  ('historical-epic', 'epic-adventure', 'slavery', 0.3),
  ('historical-epic', 'epic-adventure', 'economics', 0.3),
  ('historical-epic', 'epic-adventure', 'food', 0.2),
  ('quiet-melancholy', 'emotional-core', 'episodic', 0.9),
  ('quiet-melancholy', 'emotional-core', 'genre:drama', 0.8),
  ('quiet-melancholy', 'emotional-core', 'iyashikei', 0.8),
  ('quiet-melancholy', 'emotional-core', 'rural', 0.8),
  ('quiet-melancholy', 'emotional-core', 'ghost', 0.7),
  ('quiet-melancholy', 'emotional-core', 'afterlife', 0.6),
  ('quiet-melancholy', 'emotional-core', 'travel', 0.6),
  ('quiet-melancholy', 'emotional-core', 'philosophy', 0.6),
  ('quiet-melancholy', 'emotional-core', 'youkai', 0.5),
  ('quiet-melancholy', 'emotional-core', 'environmental', 0.5),
  ('quiet-melancholy', 'emotional-core', 'genre:supernatural', 0.5),
  ('quiet-melancholy', 'emotional-core', 'historical', 0.4),
  ('quiet-melancholy', 'emotional-core', 'tragedy', 0.4),
  ('quiet-melancholy', 'emotional-core', 'genre:slice of life', 0.4),
  ('quiet-melancholy', 'emotional-core', 'primarily adult cast', 0.4),
  ('quiet-melancholy', 'emotional-core', 'war', 0.3),
  ('quiet-melancholy', 'emotional-core', 'disability', 0.3),
  ('quiet-melancholy', 'emotional-core', 'coastal', 0.3),
  ('quiet-melancholy', 'emotional-core', 'seinen', 0.3),
  ('quiet-melancholy', 'emotional-core', 'amnesia', 0.3),
  ('romance-slow-burn', 'emotional-core', 'genre:romance', 1),
  ('romance-slow-burn', 'emotional-core', 'unrequited love', 0.8),
  ('romance-slow-burn', 'emotional-core', 'love triangle', 0.7),
  ('romance-slow-burn', 'emotional-core', 'genre:drama', 0.6),
  ('romance-slow-burn', 'emotional-core', 'heterosexual', 0.6),
  ('romance-slow-burn', 'emotional-core', 'shoujo', 0.6),
  ('romance-slow-burn', 'emotional-core', 'female protagonist', 0.5),
  ('romance-slow-burn', 'emotional-core', 'cohabitation', 0.5),
  ('romance-slow-burn', 'emotional-core', 'josei', 0.4),
  ('romance-slow-burn', 'emotional-core', 'school', 0.4),
  ('romance-slow-burn', 'emotional-core', 'age gap', 0.3),
  ('romance-slow-burn', 'emotional-core', 'fake relationship', 0.3),
  ('romance-slow-burn', 'emotional-core', 'arranged marriage', 0.3),
  ('romance-slow-burn', 'emotional-core', 'tragedy', 0.3),
  ('romance-slow-burn', 'emotional-core', 'estranged family', 0.3),
  ('romance-slow-burn', 'emotional-core', 'genre:music', 0.3),
  ('romance-slow-burn', 'emotional-core', 'curses', 0.2),
  ('romance-slow-burn', 'emotional-core', 'seinen', 0.2),
  ('slice-of-life-iyashikei', 'emotional-core', 'genre:slice of life', 1),
  ('slice-of-life-iyashikei', 'emotional-core', 'iyashikei', 1),
  ('slice-of-life-iyashikei', 'emotional-core', 'rural', 0.7),
  ('slice-of-life-iyashikei', 'emotional-core', 'camping', 0.6),
  ('slice-of-life-iyashikei', 'emotional-core', 'outdoor activities', 0.6),
  ('slice-of-life-iyashikei', 'emotional-core', 'episodic', 0.6),
  ('slice-of-life-iyashikei', 'emotional-core', 'family life', 0.5),
  ('slice-of-life-iyashikei', 'emotional-core', 'genre:comedy', 0.4),
  ('slice-of-life-iyashikei', 'emotional-core', 'agriculture', 0.4),
  ('slice-of-life-iyashikei', 'emotional-core', 'food', 0.4),
  ('slice-of-life-iyashikei', 'emotional-core', 'coastal', 0.4),
  ('slice-of-life-iyashikei', 'emotional-core', 'cute girls doing cute things', 0.4),
  ('slice-of-life-iyashikei', 'emotional-core', 'primarily adult cast', 0.3),
  ('slice-of-life-iyashikei', 'emotional-core', 'school', 0.3),
  ('slice-of-life-iyashikei', 'emotional-core', 'horticulture', 0.3),
  ('slice-of-life-iyashikei', 'emotional-core', 'inn', 0.3),
  ('slice-of-life-iyashikei', 'emotional-core', 'calligraphy', 0.3),
  ('slice-of-life-iyashikei', 'emotional-core', 'genre:sci-fi', 0.2),
  ('slice-of-life-iyashikei', 'emotional-core', 'animals', 0.2),
  ('slice-of-life-iyashikei', 'emotional-core', 'work', 0.2),
  ('coming-of-age', 'emotional-core', 'coming of age', 1),
  ('coming-of-age', 'emotional-core', 'school', 0.7),
  ('coming-of-age', 'emotional-core', 'primarily teen cast', 0.7),
  ('coming-of-age', 'emotional-core', 'genre:drama', 0.6),
  ('coming-of-age', 'emotional-core', 'bullying', 0.5),
  ('coming-of-age', 'emotional-core', 'family life', 0.5),
  ('coming-of-age', 'emotional-core', 'primarily child cast', 0.4),
  ('coming-of-age', 'emotional-core', 'college', 0.4),
  ('coming-of-age', 'emotional-core', 'seinen', 0.4),
  ('coming-of-age', 'emotional-core', 'genre:supernatural', 0.3),
  ('coming-of-age', 'emotional-core', 'genre:fantasy', 0.3),
  ('coming-of-age', 'emotional-core', 'genre:romance', 0.3),
  ('coming-of-age', 'emotional-core', 'josei', 0.3),
  ('coming-of-age', 'emotional-core', 'found family', 0.3),
  ('coming-of-age', 'emotional-core', 'shogi', 0.3),
  ('coming-of-age', 'emotional-core', 'disability', 0.3),
  ('coming-of-age', 'emotional-core', 'youkai', 0.2),
  ('coming-of-age', 'emotional-core', 'suicide', 0.2),
  ('tragedy-tearjerker', 'emotional-core', 'tragedy', 1),
  ('tragedy-tearjerker', 'emotional-core', 'genre:drama', 0.8),
  ('tragedy-tearjerker', 'emotional-core', 'afterlife', 0.5),
  ('tragedy-tearjerker', 'emotional-core', 'ghost', 0.5),
  ('tragedy-tearjerker', 'emotional-core', 'war', 0.4),
  ('tragedy-tearjerker', 'emotional-core', 'parenthood', 0.4),
  ('tragedy-tearjerker', 'emotional-core', 'family life', 0.4),
  ('tragedy-tearjerker', 'emotional-core', 'genre:romance', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'school', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'suicide', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'natural disaster', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'disability', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'orphan', 0.3),
  ('tragedy-tearjerker', 'emotional-core', 'primarily child cast', 0.2),
  ('tragedy-tearjerker', 'emotional-core', 'unrequited love', 0.2),
  ('tragedy-tearjerker', 'emotional-core', 'historical', 0.2),
  ('psychological-thriller', 'mind-thrill', 'genre:psychological', 1),
  ('psychological-thriller', 'mind-thrill', 'genre:thriller', 0.9),
  ('psychological-thriller', 'mind-thrill', 'conspiracy', 0.7),
  ('psychological-thriller', 'mind-thrill', 'crime', 0.6),
  ('psychological-thriller', 'mind-thrill', 'detective', 0.6),
  ('psychological-thriller', 'mind-thrill', 'police', 0.6),
  ('psychological-thriller', 'mind-thrill', 'anti-hero', 0.5),
  ('psychological-thriller', 'mind-thrill', 'seinen', 0.5),
  ('psychological-thriller', 'mind-thrill', 'memory manipulation', 0.5),
  ('psychological-thriller', 'mind-thrill', 'dissociative identities', 0.4),
  ('psychological-thriller', 'mind-thrill', 'philosophy', 0.4),
  ('psychological-thriller', 'mind-thrill', 'fugitive', 0.4),
  ('psychological-thriller', 'mind-thrill', 'dystopian', 0.4),
  ('psychological-thriller', 'mind-thrill', 'genre:mystery', 0.4),
  ('psychological-thriller', 'mind-thrill', 'terrorism', 0.3),
  ('psychological-thriller', 'mind-thrill', 'blackmail', 0.3),
  ('psychological-thriller', 'mind-thrill', 'medicine', 0.3),
  ('psychological-thriller', 'mind-thrill', 'gods', 0.3),
  ('psychological-thriller', 'mind-thrill', 'urban', 0.3),
  ('psychological-thriller', 'mind-thrill', 'guns', 0.3),
  ('psychological-thriller', 'mind-thrill', 'cyberpunk', 0.2),
  ('psychological-thriller', 'mind-thrill', 'shounen', 0.2),
  ('mystery-detective', 'mind-thrill', 'genre:mystery', 1),
  ('mystery-detective', 'mind-thrill', 'detective', 1),
  ('mystery-detective', 'mind-thrill', 'police', 0.7),
  ('mystery-detective', 'mind-thrill', 'crime', 0.7),
  ('mystery-detective', 'mind-thrill', 'conspiracy', 0.5),
  ('mystery-detective', 'mind-thrill', 'episodic', 0.5),
  ('mystery-detective', 'mind-thrill', 'school', 0.5),
  ('mystery-detective', 'mind-thrill', 'amnesia', 0.4),
  ('mystery-detective', 'mind-thrill', 'time manipulation', 0.4),
  ('mystery-detective', 'mind-thrill', 'fugitive', 0.3),
  ('mystery-detective', 'mind-thrill', 'blackmail', 0.3),
  ('mystery-detective', 'mind-thrill', 'urban', 0.3),
  ('mystery-detective', 'mind-thrill', 'seinen', 0.3),
  ('mystery-detective', 'mind-thrill', 'genre:thriller', 0.3),
  ('mystery-detective', 'mind-thrill', 'primarily teen cast', 0.3),
  ('mystery-detective', 'mind-thrill', 'shounen', 0.2),
  ('mystery-detective', 'mind-thrill', 'primarily child cast', 0.2),
  ('mystery-detective', 'mind-thrill', 'drugs', 0.2),
  ('mystery-detective', 'mind-thrill', 'historical', 0.2),
  ('horror-dread', 'mind-thrill', 'genre:horror', 1),
  ('horror-dread', 'mind-thrill', 'ghost', 0.8),
  ('horror-dread', 'mind-thrill', 'gore', 0.7),
  ('horror-dread', 'mind-thrill', 'curses', 0.7),
  ('horror-dread', 'mind-thrill', 'body horror', 0.7),
  ('horror-dread', 'mind-thrill', 'survival', 0.6),
  ('horror-dread', 'mind-thrill', 'rural', 0.5),
  ('horror-dread', 'mind-thrill', 'school', 0.5),
  ('horror-dread', 'mind-thrill', 'zombie', 0.5),
  ('horror-dread', 'mind-thrill', 'cosmic horror', 0.5),
  ('horror-dread', 'mind-thrill', 'genre:psychological', 0.5),
  ('horror-dread', 'mind-thrill', 'vampire', 0.4),
  ('horror-dread', 'mind-thrill', 'torture', 0.4),
  ('horror-dread', 'mind-thrill', 'time loop', 0.4),
  ('horror-dread', 'mind-thrill', 'tragedy', 0.3),
  ('horror-dread', 'mind-thrill', 'cult', 0.3),
  ('horror-dread', 'mind-thrill', 'anthology', 0.3),
  ('horror-dread', 'mind-thrill', 'seinen', 0.3),
  ('horror-dread', 'mind-thrill', 'demons', 0.3),
  ('horror-dread', 'mind-thrill', 'ero guro', 0.3),
  ('horror-dread', 'mind-thrill', 'genre:thriller', 0.3),
  ('horror-dread', 'mind-thrill', 'genre:mystery', 0.3),
  ('horror-dread', 'mind-thrill', 'episodic', 0.2),
  ('horror-dread', 'mind-thrill', 'cannibalism', 0.2),
  ('mind-game-strategy', 'mind-thrill', 'gambling', 1),
  ('mind-game-strategy', 'mind-thrill', 'death game', 0.9),
  ('mind-game-strategy', 'mind-thrill', 'proxy battle', 0.8),
  ('mind-game-strategy', 'mind-thrill', 'mahjong', 0.7),
  ('mind-game-strategy', 'mind-thrill', 'genre:psychological', 0.7),
  ('mind-game-strategy', 'mind-thrill', 'battle royale', 0.6),
  ('mind-game-strategy', 'mind-thrill', 'card battle', 0.5),
  ('mind-game-strategy', 'mind-thrill', 'survival', 0.5),
  ('mind-game-strategy', 'mind-thrill', 'poker', 0.5),
  ('mind-game-strategy', 'mind-thrill', 'seinen', 0.5),
  ('mind-game-strategy', 'mind-thrill', 'go', 0.4),
  ('mind-game-strategy', 'mind-thrill', 'afterlife', 0.4),
  ('mind-game-strategy', 'mind-thrill', 'e-sports', 0.4),
  ('mind-game-strategy', 'mind-thrill', 'blackmail', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'crime', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'yakuza', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'shogi', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'bar', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'board game', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'video games', 0.3),
  ('mind-game-strategy', 'mind-thrill', 'economics', 0.2),
  ('sci-fi-space', 'speculative-worlds', 'genre:sci-fi', 1),
  ('sci-fi-space', 'speculative-worlds', 'space', 1),
  ('sci-fi-space', 'speculative-worlds', 'space opera', 0.9),
  ('sci-fi-space', 'speculative-worlds', 'aliens', 0.7),
  ('sci-fi-space', 'speculative-worlds', 'robots', 0.6),
  ('sci-fi-space', 'speculative-worlds', 'artificial intelligence', 0.6),
  ('sci-fi-space', 'speculative-worlds', 'ships', 0.5),
  ('sci-fi-space', 'speculative-worlds', 'travel', 0.4),
  ('sci-fi-space', 'speculative-worlds', 'cyborg', 0.4),
  ('sci-fi-space', 'speculative-worlds', 'seinen', 0.4),
  ('sci-fi-space', 'speculative-worlds', 'politics', 0.4),
  ('sci-fi-space', 'speculative-worlds', 'primarily adult cast', 0.4),
  ('sci-fi-space', 'speculative-worlds', 'war', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'work', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'astronomy', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'episodic', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'cowboys', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'military', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'genre:drama', 0.3),
  ('sci-fi-space', 'speculative-worlds', 'noir', 0.2),
  ('mecha', 'speculative-worlds', 'genre:mecha', 1),
  ('mecha', 'speculative-worlds', 'real robot', 1),
  ('mecha', 'speculative-worlds', 'super robot', 0.9),
  ('mecha', 'speculative-worlds', 'robots', 0.8),
  ('mecha', 'speculative-worlds', 'genre:sci-fi', 0.7),
  ('mecha', 'speculative-worlds', 'war', 0.6),
  ('mecha', 'speculative-worlds', 'military', 0.6),
  ('mecha', 'speculative-worlds', 'space', 0.5),
  ('mecha', 'speculative-worlds', 'politics', 0.5),
  ('mecha', 'speculative-worlds', 'conspiracy', 0.4),
  ('mecha', 'speculative-worlds', 'primarily teen cast', 0.4),
  ('mecha', 'speculative-worlds', 'genre:psychological', 0.4),
  ('mecha', 'speculative-worlds', 'aliens', 0.3),
  ('mecha', 'speculative-worlds', 'shounen', 0.3),
  ('mecha', 'speculative-worlds', 'seinen', 0.3),
  ('mecha', 'speculative-worlds', 'tragedy', 0.3),
  ('mecha', 'speculative-worlds', 'coming of age', 0.3),
  ('mecha', 'speculative-worlds', 'kaiju', 0.3),
  ('mecha', 'speculative-worlds', 'genre:drama', 0.3),
  ('mecha', 'speculative-worlds', 'space opera', 0.3),
  ('mecha', 'speculative-worlds', 'terrorism', 0.2),
  ('cyberpunk-dystopia', 'speculative-worlds', 'cyberpunk', 1),
  ('cyberpunk-dystopia', 'speculative-worlds', 'dystopian', 1),
  ('cyberpunk-dystopia', 'speculative-worlds', 'genre:sci-fi', 0.8),
  ('cyberpunk-dystopia', 'speculative-worlds', 'artificial intelligence', 0.7),
  ('cyberpunk-dystopia', 'speculative-worlds', 'cyborg', 0.7),
  ('cyberpunk-dystopia', 'speculative-worlds', 'noir', 0.6),
  ('cyberpunk-dystopia', 'speculative-worlds', 'urban', 0.6),
  ('cyberpunk-dystopia', 'speculative-worlds', 'police', 0.5),
  ('cyberpunk-dystopia', 'speculative-worlds', 'conspiracy', 0.5),
  ('cyberpunk-dystopia', 'speculative-worlds', 'philosophy', 0.5),
  ('cyberpunk-dystopia', 'speculative-worlds', 'guns', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'post-apocalyptic', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'robots', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'genre:psychological', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'seinen', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'augmented reality', 0.4),
  ('cyberpunk-dystopia', 'speculative-worlds', 'terrorism', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'drugs', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'crime', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'virtual world', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'body horror', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'genre:thriller', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'motorcycles', 0.3),
  ('cyberpunk-dystopia', 'speculative-worlds', 'super power', 0.2),
  ('time-parallel-worlds', 'speculative-worlds', 'time manipulation', 1),
  ('time-parallel-worlds', 'speculative-worlds', 'time loop', 1),
  ('time-parallel-worlds', 'speculative-worlds', 'alternate universe', 0.9),
  ('time-parallel-worlds', 'speculative-worlds', 'time skip', 0.6),
  ('time-parallel-worlds', 'speculative-worlds', 'genre:sci-fi', 0.6),
  ('time-parallel-worlds', 'speculative-worlds', 'genre:mystery', 0.5),
  ('time-parallel-worlds', 'speculative-worlds', 'conspiracy', 0.4),
  ('time-parallel-worlds', 'speculative-worlds', 'genre:thriller', 0.4),
  ('time-parallel-worlds', 'speculative-worlds', 'body swapping', 0.4),
  ('time-parallel-worlds', 'speculative-worlds', 'achronological order', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'amnesia', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'coastal', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'genre:supernatural', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'tragedy', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'seinen', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'genre:drama', 0.3),
  ('time-parallel-worlds', 'speculative-worlds', 'urban', 0.2),
  ('time-parallel-worlds', 'speculative-worlds', 'chuunibyou', 0.2),
  ('auteur-cinema', 'craft-art', 'environmental', 0.7),
  ('auteur-cinema', 'craft-art', 'rural', 0.7),
  ('auteur-cinema', 'craft-art', 'family life', 0.7),
  ('auteur-cinema', 'craft-art', 'historical', 0.6),
  ('auteur-cinema', 'craft-art', 'genre:fantasy', 0.6),
  ('auteur-cinema', 'craft-art', 'genre:drama', 0.6),
  ('auteur-cinema', 'craft-art', 'coming of age', 0.6),
  ('auteur-cinema', 'craft-art', 'war', 0.5),
  ('auteur-cinema', 'craft-art', 'unrequited love', 0.5),
  ('auteur-cinema', 'craft-art', 'urban', 0.5),
  ('auteur-cinema', 'craft-art', 'fairy tale', 0.5),
  ('auteur-cinema', 'craft-art', 'mythology', 0.5),
  ('auteur-cinema', 'craft-art', 'youkai', 0.5),
  ('auteur-cinema', 'craft-art', 'gods', 0.5),
  ('auteur-cinema', 'craft-art', 'witch', 0.5),
  ('auteur-cinema', 'craft-art', 'parenthood', 0.5),
  ('auteur-cinema', 'craft-art', 'dragons', 0.4),
  ('auteur-cinema', 'craft-art', 'body swapping', 0.4),
  ('auteur-cinema', 'craft-art', 'natural disaster', 0.4),
  ('auteur-cinema', 'craft-art', 'idol', 0.4),
  ('auteur-cinema', 'craft-art', 'acting', 0.4),
  ('auteur-cinema', 'craft-art', 'genre:psychological', 0.4),
  ('auteur-cinema', 'craft-art', 'genre:romance', 0.4),
  ('auteur-cinema', 'craft-art', 'genre:adventure', 0.4),
  ('auteur-cinema', 'craft-art', 'homeless', 0.3),
  ('auteur-cinema', 'craft-art', 'memory manipulation', 0.3),
  ('auteur-cinema', 'craft-art', 'shapeshifting', 0.3),
  ('auteur-cinema', 'craft-art', 'anthropomorphism', 0.3),
  ('auteur-cinema', 'craft-art', 'aviation', 0.3),
  ('auteur-cinema', 'craft-art', 'steampunk', 0.3),
  ('arthouse-experimental', 'craft-art', 'rotoscoping', 0.7),
  ('arthouse-experimental', 'craft-art', 'anthology', 0.7),
  ('arthouse-experimental', 'craft-art', 'no dialogue', 0.7),
  ('arthouse-experimental', 'craft-art', 'philosophy', 0.7),
  ('arthouse-experimental', 'craft-art', 'genre:psychological', 0.6),
  ('arthouse-experimental', 'craft-art', 'memory manipulation', 0.6),
  ('arthouse-experimental', 'craft-art', 'college', 0.5),
  ('arthouse-experimental', 'craft-art', 'surreal comedy', 0.5),
  ('arthouse-experimental', 'craft-art', 'denpa', 0.5),
  ('arthouse-experimental', 'craft-art', 'achronological order', 0.5),
  ('arthouse-experimental', 'craft-art', 'psychosexual', 0.4),
  ('arthouse-experimental', 'craft-art', 'body swapping', 0.4),
  ('arthouse-experimental', 'craft-art', 'episodic', 0.4),
  ('arthouse-experimental', 'craft-art', 'seinen', 0.4),
  ('arthouse-experimental', 'craft-art', 'genre:drama', 0.4),
  ('arthouse-experimental', 'craft-art', 'space', 0.3),
  ('arthouse-experimental', 'craft-art', 'pov', 0.3),
  ('arthouse-experimental', 'craft-art', 'mixed media', 0.3),
  ('arthouse-experimental', 'craft-art', 'table tennis', 0.3),
  ('arthouse-experimental', 'craft-art', 'coming of age', 0.3),
  ('arthouse-experimental', 'craft-art', 'urban', 0.3),
  ('arthouse-experimental', 'craft-art', 'genre:comedy', 0.2),
  ('classic-serial-canon', 'craft-art', 'ensemble cast', 0.9),
  ('classic-serial-canon', 'craft-art', 'politics', 0.8),
  ('classic-serial-canon', 'craft-art', 'war', 0.8),
  ('classic-serial-canon', 'craft-art', 'military', 0.7),
  ('classic-serial-canon', 'craft-art', 'alchemy', 0.7),
  ('classic-serial-canon', 'craft-art', 'space opera', 0.7),
  ('classic-serial-canon', 'craft-art', 'conspiracy', 0.6),
  ('classic-serial-canon', 'craft-art', 'philosophy', 0.6),
  ('classic-serial-canon', 'craft-art', 'genre:drama', 0.6),
  ('classic-serial-canon', 'craft-art', 'tragedy', 0.5),
  ('classic-serial-canon', 'craft-art', 'revenge', 0.5),
  ('classic-serial-canon', 'craft-art', 'genre:action', 0.5),
  ('classic-serial-canon', 'craft-art', 'genre:sci-fi', 0.4),
  ('classic-serial-canon', 'craft-art', 'genre:fantasy', 0.4),
  ('classic-serial-canon', 'craft-art', 'genre:adventure', 0.4),
  ('classic-serial-canon', 'craft-art', 'shounen', 0.4),
  ('classic-serial-canon', 'craft-art', 'human experimentation', 0.4),
  ('classic-serial-canon', 'craft-art', 'seinen', 0.3),
  ('classic-serial-canon', 'craft-art', 'religion', 0.3),
  ('classic-serial-canon', 'craft-art', 'steampunk', 0.3),
  ('classic-serial-canon', 'craft-art', 'coming of age', 0.3),
  ('classic-serial-canon', 'craft-art', 'primarily male cast', 0.3),
  ('comedy-parody', 'laughter', 'genre:comedy', 1),
  ('comedy-parody', 'laughter', 'parody', 1),
  ('comedy-parody', 'laughter', 'satire', 0.8),
  ('comedy-parody', 'laughter', 'slapstick', 0.8),
  ('comedy-parody', 'laughter', 'surreal comedy', 0.8),
  ('comedy-parody', 'laughter', 'meta', 0.7),
  ('comedy-parody', 'laughter', 'manzai', 0.6),
  ('comedy-parody', 'laughter', 'otaku culture', 0.5),
  ('comedy-parody', 'laughter', '4-koma', 0.5),
  ('comedy-parody', 'laughter', 'episodic', 0.5),
  ('comedy-parody', 'laughter', 'school', 0.4),
  ('comedy-parody', 'laughter', 'chibi', 0.3),
  ('comedy-parody', 'laughter', 'genre:slice of life', 0.3),
  ('comedy-parody', 'laughter', 'primarily teen cast', 0.3),
  ('comedy-parody', 'laughter', 'shounen', 0.3),
  ('comedy-parody', 'laughter', 'crossdressing', 0.2),
  ('comedy-parody', 'laughter', 'aliens', 0.2),
  ('comedy-parody', 'laughter', 'genre:fantasy', 0.2),
  ('romantic-comedy', 'laughter', 'genre:romance', 1),
  ('romantic-comedy', 'laughter', 'genre:comedy', 1),
  ('romantic-comedy', 'laughter', 'tsundere', 0.7),
  ('romantic-comedy', 'laughter', 'school', 0.6),
  ('romantic-comedy', 'laughter', 'love triangle', 0.6),
  ('romantic-comedy', 'laughter', 'unrequited love', 0.5),
  ('romantic-comedy', 'laughter', 'primarily teen cast', 0.5),
  ('romantic-comedy', 'laughter', 'ojou-sama', 0.4),
  ('romantic-comedy', 'laughter', 'fake relationship', 0.4),
  ('romantic-comedy', 'laughter', 'cohabitation', 0.3),
  ('romantic-comedy', 'laughter', 'kuudere', 0.3),
  ('romantic-comedy', 'laughter', 'seinen', 0.3),
  ('romantic-comedy', 'laughter', 'shoujo', 0.3),
  ('romantic-comedy', 'laughter', 'shounen', 0.3),
  ('romantic-comedy', 'laughter', 'gyaru', 0.3),
  ('romantic-comedy', 'laughter', 'episodic', 0.3),
  ('romantic-comedy', 'laughter', 'genre:slice of life', 0.3),
  ('romantic-comedy', 'laughter', 'male protagonist', 0.3),
  ('romantic-comedy', 'laughter', 'female harem', 0.2),
  ('romantic-comedy', 'laughter', 'chuunibyou', 0.2),
  ('romantic-comedy', 'laughter', 'otaku culture', 0.2),
  ('sports-competition', 'life-world', 'genre:sports', 1),
  ('sports-competition', 'life-world', 'volleyball', 0.7),
  ('sports-competition', 'life-world', 'basketball', 0.7),
  ('sports-competition', 'life-world', 'baseball', 0.7),
  ('sports-competition', 'life-world', 'football', 0.7),
  ('sports-competition', 'life-world', 'karuta', 0.7),
  ('sports-competition', 'life-world', 'boxing', 0.6),
  ('sports-competition', 'life-world', 'tennis', 0.6),
  ('sports-competition', 'life-world', 'swimming', 0.6),
  ('sports-competition', 'life-world', 'athletics', 0.5),
  ('sports-competition', 'life-world', 'ice skating', 0.5),
  ('sports-competition', 'life-world', 'cycling', 0.5),
  ('sports-competition', 'life-world', 'american football', 0.5),
  ('sports-competition', 'life-world', 'badminton', 0.5),
  ('sports-competition', 'life-world', 'table tennis', 0.4),
  ('sports-competition', 'life-world', 'judo', 0.4),
  ('sports-competition', 'life-world', 'wrestling', 0.4),
  ('sports-competition', 'life-world', 'sumo', 0.4),
  ('sports-competition', 'life-world', 'shounen', 0.4),
  ('sports-competition', 'life-world', 'school', 0.4),
  ('sports-competition', 'life-world', 'primarily teen cast', 0.4),
  ('sports-competition', 'life-world', 'fencing', 0.3),
  ('sports-competition', 'life-world', 'archery', 0.3),
  ('sports-competition', 'life-world', 'rugby', 0.3),
  ('sports-competition', 'life-world', 'skateboarding', 0.3),
  ('sports-competition', 'life-world', 'ensemble cast', 0.3),
  ('sports-competition', 'life-world', 'coming of age', 0.3),
  ('sports-competition', 'life-world', 'surfing', 0.2),
  ('music-performance', 'life-world', 'genre:music', 1),
  ('music-performance', 'life-world', 'band', 0.9),
  ('music-performance', 'life-world', 'classical music', 0.8),
  ('music-performance', 'life-world', 'jazz music', 0.7),
  ('music-performance', 'life-world', 'rock music', 0.7),
  ('music-performance', 'life-world', 'dancing', 0.6),
  ('music-performance', 'life-world', 'musical theater', 0.6),
  ('music-performance', 'life-world', 'ballet', 0.5),
  ('music-performance', 'life-world', 'hip-hop music', 0.5),
  ('music-performance', 'life-world', 'school club', 0.5),
  ('music-performance', 'life-world', 'metal music', 0.4),
  ('music-performance', 'life-world', 'school', 0.4),
  ('music-performance', 'life-world', 'genre:drama', 0.4),
  ('music-performance', 'life-world', 'acting', 0.3),
  ('music-performance', 'life-world', 'idol', 0.3),
  ('music-performance', 'life-world', 'coming of age', 0.3),
  ('music-performance', 'life-world', 'josei', 0.3),
  ('music-performance', 'life-world', 'vocal synth', 0.3),
  ('music-performance', 'life-world', 'primarily teen cast', 0.3),
  ('music-performance', 'life-world', 'genre:comedy', 0.3),
  ('music-performance', 'life-world', 'genre:slice of life', 0.3),
  ('music-performance', 'life-world', 'tragedy', 0.2),
  ('music-performance', 'life-world', 'genre:romance', 0.2),
  ('food-craft', 'life-world', 'food', 1),
  ('food-craft', 'life-world', 'restaurant', 0.8),
  ('food-craft', 'life-world', 'bar', 0.7),
  ('food-craft', 'life-world', 'school', 0.5),
  ('food-craft', 'life-world', 'rakugo', 0.5),
  ('food-craft', 'life-world', 'drawing', 0.5),
  ('food-craft', 'life-world', 'shounen', 0.4),
  ('food-craft', 'life-world', 'dungeon', 0.4),
  ('food-craft', 'life-world', 'agriculture', 0.4),
  ('food-craft', 'life-world', 'fishing', 0.4),
  ('food-craft', 'life-world', 'calligraphy', 0.4),
  ('food-craft', 'life-world', 'fashion', 0.4),
  ('food-craft', 'life-world', 'work', 0.4),
  ('food-craft', 'life-world', 'genre:slice of life', 0.4),
  ('food-craft', 'life-world', 'photography', 0.3),
  ('food-craft', 'life-world', 'kabuki', 0.3),
  ('food-craft', 'life-world', 'writing', 0.3),
  ('food-craft', 'life-world', 'filmmaking', 0.3),
  ('food-craft', 'life-world', 'seinen', 0.3),
  ('food-craft', 'life-world', 'genre:drama', 0.3),
  ('food-craft', 'life-world', 'genre:comedy', 0.3),
  ('food-craft', 'life-world', 'episodic', 0.3),
  ('food-craft', 'life-world', 'primarily adult cast', 0.3),
  ('workplace-adult-life', 'life-world', 'work', 1),
  ('workplace-adult-life', 'life-world', 'office', 0.9),
  ('workplace-adult-life', 'life-world', 'primarily adult cast', 0.9),
  ('workplace-adult-life', 'life-world', 'genre:slice of life', 0.6),
  ('workplace-adult-life', 'life-world', 'seinen', 0.6),
  ('workplace-adult-life', 'life-world', 'office lady', 0.6),
  ('workplace-adult-life', 'life-world', 'otaku culture', 0.5),
  ('workplace-adult-life', 'life-world', 'josei', 0.5),
  ('workplace-adult-life', 'life-world', 'genre:comedy', 0.5),
  ('workplace-adult-life', 'life-world', 'anthropomorphism', 0.4),
  ('workplace-adult-life', 'life-world', 'filmmaking', 0.4),
  ('workplace-adult-life', 'life-world', 'software development', 0.4),
  ('workplace-adult-life', 'life-world', 'genre:drama', 0.4),
  ('workplace-adult-life', 'life-world', 'video games', 0.3),
  ('workplace-adult-life', 'life-world', 'economics', 0.3),
  ('workplace-adult-life', 'life-world', 'genre:romance', 0.3),
  ('workplace-adult-life', 'life-world', 'episodic', 0.3),
  ('workplace-adult-life', 'life-world', 'urban', 0.3),
  ('workplace-adult-life', 'life-world', 'female protagonist', 0.3),
  ('workplace-adult-life', 'life-world', 'konbini', 0.3),
  ('workplace-adult-life', 'life-world', 'restaurant', 0.2),
  ('war-military', 'intense', 'war', 1),
  ('war-military', 'intense', 'military', 1),
  ('war-military', 'intense', 'politics', 0.7),
  ('war-military', 'intense', 'guns', 0.6),
  ('war-military', 'intense', 'historical', 0.6),
  ('war-military', 'intense', 'seinen', 0.5),
  ('war-military', 'intense', 'tanks', 0.5),
  ('war-military', 'intense', 'tragedy', 0.5),
  ('war-military', 'intense', 'genre:drama', 0.5),
  ('war-military', 'intense', 'genre:action', 0.5),
  ('war-military', 'intense', 'space opera', 0.4),
  ('war-military', 'intense', 'ensemble cast', 0.4),
  ('war-military', 'intense', 'space', 0.3),
  ('war-military', 'intense', 'genre:mecha', 0.3),
  ('war-military', 'intense', 'real robot', 0.3),
  ('war-military', 'intense', 'espionage', 0.3),
  ('war-military', 'intense', 'kingdom management', 0.3),
  ('war-military', 'intense', 'royal affairs', 0.3),
  ('war-military', 'intense', 'magic', 0.3),
  ('war-military', 'intense', 'survival', 0.3),
  ('war-military', 'intense', 'genre:thriller', 0.3),
  ('war-military', 'intense', 'terrorism', 0.2),
  ('war-military', 'intense', 'female protagonist', 0.2),
  ('crime-underworld', 'intense', 'crime', 1),
  ('crime-underworld', 'intense', 'criminal organization', 1),
  ('crime-underworld', 'intense', 'mafia', 0.9),
  ('crime-underworld', 'intense', 'yakuza', 0.8),
  ('crime-underworld', 'intense', 'gangs', 0.8),
  ('crime-underworld', 'intense', 'noir', 0.7),
  ('crime-underworld', 'intense', 'guns', 0.6),
  ('crime-underworld', 'intense', 'drugs', 0.6),
  ('crime-underworld', 'intense', 'revenge', 0.6),
  ('crime-underworld', 'intense', 'genre:thriller', 0.6),
  ('crime-underworld', 'intense', 'triads', 0.5),
  ('crime-underworld', 'intense', 'fugitive', 0.5),
  ('crime-underworld', 'intense', 'urban', 0.5),
  ('crime-underworld', 'intense', 'seinen', 0.5),
  ('crime-underworld', 'intense', 'assassins', 0.5),
  ('crime-underworld', 'intense', 'genre:action', 0.5),
  ('crime-underworld', 'intense', 'police', 0.4),
  ('crime-underworld', 'intense', 'genre:drama', 0.4),
  ('crime-underworld', 'intense', 'conspiracy', 0.3),
  ('crime-underworld', 'intense', 'blackmail', 0.3),
  ('crime-underworld', 'intense', 'historical', 0.3),
  ('crime-underworld', 'intense', 'torture', 0.2),
  ('crime-underworld', 'intense', 'prostitution', 0.2),
  ('crime-underworld', 'intense', 'genre:mystery', 0.2),
  ('supernatural-yokai', 'intense', 'genre:supernatural', 1),
  ('supernatural-yokai', 'intense', 'youkai', 1),
  ('supernatural-yokai', 'intense', 'ghost', 0.8),
  ('supernatural-yokai', 'intense', 'exorcism', 0.7),
  ('supernatural-yokai', 'intense', 'mythology', 0.6),
  ('supernatural-yokai', 'intense', 'gods', 0.6),
  ('supernatural-yokai', 'intense', 'shrine maiden', 0.5),
  ('supernatural-yokai', 'intense', 'rural', 0.5),
  ('supernatural-yokai', 'intense', 'episodic', 0.5),
  ('supernatural-yokai', 'intense', 'urban fantasy', 0.5),
  ('supernatural-yokai', 'intense', 'demons', 0.4),
  ('supernatural-yokai', 'intense', 'curses', 0.4),
  ('supernatural-yokai', 'intense', 'afterlife', 0.4),
  ('supernatural-yokai', 'intense', 'historical', 0.4),
  ('supernatural-yokai', 'intense', 'genre:fantasy', 0.4),
  ('supernatural-yokai', 'intense', 'genre:drama', 0.4),
  ('supernatural-yokai', 'intense', 'iyashikei', 0.3),
  ('supernatural-yokai', 'intense', 'genre:mystery', 0.3),
  ('supernatural-yokai', 'intense', 'seinen', 0.3),
  ('supernatural-yokai', 'intense', 'shounen', 0.2),
  ('supernatural-yokai', 'intense', 'school', 0.2),
  ('bl-yuri', 'relationships-identity', 'boys'' love', 1),
  ('bl-yuri', 'relationships-identity', 'yuri', 1),
  ('bl-yuri', 'relationships-identity', 'lgbtq+ themes', 0.9),
  ('bl-yuri', 'relationships-identity', 'genre:romance', 0.7),
  ('bl-yuri', 'relationships-identity', 'genre:drama', 0.5),
  ('bl-yuri', 'relationships-identity', 'band', 0.4),
  ('bl-yuri', 'relationships-identity', 'aromantic', 0.4),
  ('bl-yuri', 'relationships-identity', 'omegaverse', 0.4),
  ('bl-yuri', 'relationships-identity', 'primarily male cast', 0.4),
  ('bl-yuri', 'relationships-identity', 'primarily female cast', 0.4),
  ('bl-yuri', 'relationships-identity', 'school', 0.4),
  ('bl-yuri', 'relationships-identity', 'genre:music', 0.3),
  ('bl-yuri', 'relationships-identity', 'bisexual', 0.3),
  ('bl-yuri', 'relationships-identity', 'transgender', 0.3),
  ('bl-yuri', 'relationships-identity', 'shoujo', 0.3),
  ('bl-yuri', 'relationships-identity', 'josei', 0.3),
  ('bl-yuri', 'relationships-identity', 'seinen', 0.3),
  ('bl-yuri', 'relationships-identity', 'unrequited love', 0.3),
  ('bl-yuri', 'relationships-identity', 'coming of age', 0.3),
  ('bl-yuri', 'relationships-identity', 'age gap', 0.2),
  ('bl-yuri', 'relationships-identity', 'tragedy', 0.2),
  ('bl-yuri', 'relationships-identity', 'genre:slice of life', 0.2),
  ('family-generations', 'relationships-identity', 'family life', 1),
  ('family-generations', 'relationships-identity', 'parenthood', 1),
  ('family-generations', 'relationships-identity', 'adoption', 0.7),
  ('family-generations', 'relationships-identity', 'estranged family', 0.7),
  ('family-generations', 'relationships-identity', 'found family', 0.7),
  ('family-generations', 'relationships-identity', 'genre:drama', 0.6),
  ('family-generations', 'relationships-identity', 'marriage', 0.5),
  ('family-generations', 'relationships-identity', 'orphan', 0.5),
  ('family-generations', 'relationships-identity', 'genre:slice of life', 0.5),
  ('family-generations', 'relationships-identity', 'pregnancy', 0.4),
  ('family-generations', 'relationships-identity', 'primarily child cast', 0.4),
  ('family-generations', 'relationships-identity', 'rural', 0.4),
  ('family-generations', 'relationships-identity', 'time skip', 0.4),
  ('family-generations', 'relationships-identity', 'food', 0.4),
  ('family-generations', 'relationships-identity', 'iyashikei', 0.4),
  ('family-generations', 'relationships-identity', 'elderly protagonist', 0.3),
  ('family-generations', 'relationships-identity', 'twins', 0.3),
  ('family-generations', 'relationships-identity', 'genre:comedy', 0.3),
  ('family-generations', 'relationships-identity', 'genre:supernatural', 0.3),
  ('family-generations', 'relationships-identity', 'werewolf', 0.3),
  ('family-generations', 'relationships-identity', 'coming of age', 0.3),
  ('family-generations', 'relationships-identity', 'tragedy', 0.3),
  ('family-generations', 'relationships-identity', 'seinen', 0.3),
  ('family-generations', 'relationships-identity', 'josei', 0.2),
  ('idol-showbiz', 'relationships-identity', 'idol', 1),
  ('idol-showbiz', 'relationships-identity', 'genre:music', 0.7),
  ('idol-showbiz', 'relationships-identity', 'acting', 0.7),
  ('idol-showbiz', 'relationships-identity', 'dancing', 0.5),
  ('idol-showbiz', 'relationships-identity', 'musical theater', 0.5),
  ('idol-showbiz', 'relationships-identity', 'genre:drama', 0.5),
  ('idol-showbiz', 'relationships-identity', 'modeling', 0.4),
  ('idol-showbiz', 'relationships-identity', 'fashion', 0.4),
  ('idol-showbiz', 'relationships-identity', 'filmmaking', 0.4),
  ('idol-showbiz', 'relationships-identity', 'revenge', 0.4),
  ('idol-showbiz', 'relationships-identity', 'seinen', 0.4),
  ('idol-showbiz', 'relationships-identity', 'urban', 0.3),
  ('idol-showbiz', 'relationships-identity', 'genre:mystery', 0.3),
  ('idol-showbiz', 'relationships-identity', 'primarily teen cast', 0.3),
  ('idol-showbiz', 'relationships-identity', 'female protagonist', 0.3),
  ('idol-showbiz', 'relationships-identity', 'vtuber', 0.3),
  ('idol-showbiz', 'relationships-identity', 'ensemble cast', 0.3),
  ('idol-showbiz', 'relationships-identity', 'genre:comedy', 0.2),
  ('idol-showbiz', 'relationships-identity', 'male protagonist', 0.2),
  ('idol-showbiz', 'relationships-identity', 'coming of age', 0.2),
  ('moe-cgdct', 'otaku-register', 'cute girls doing cute things', 1),
  ('moe-cgdct', 'otaku-register', 'cute boys doing cute things', 0.8),
  ('moe-cgdct', 'otaku-register', 'genre:slice of life', 0.8),
  ('moe-cgdct', 'otaku-register', 'school club', 0.7),
  ('moe-cgdct', 'otaku-register', 'school', 0.6),
  ('moe-cgdct', 'otaku-register', 'iyashikei', 0.6),
  ('moe-cgdct', 'otaku-register', '4-koma', 0.6),
  ('moe-cgdct', 'otaku-register', 'primarily female cast', 0.6),
  ('moe-cgdct', 'otaku-register', 'genre:comedy', 0.5),
  ('moe-cgdct', 'otaku-register', 'episodic', 0.5),
  ('moe-cgdct', 'otaku-register', 'chibi', 0.4),
  ('moe-cgdct', 'otaku-register', 'band', 0.4),
  ('moe-cgdct', 'otaku-register', 'female protagonist', 0.4),
  ('moe-cgdct', 'otaku-register', 'seinen', 0.4),
  ('moe-cgdct', 'otaku-register', 'primarily teen cast', 0.4),
  ('moe-cgdct', 'otaku-register', 'camping', 0.3),
  ('moe-cgdct', 'otaku-register', 'otaku culture', 0.3),
  ('moe-cgdct', 'otaku-register', 'genre:music', 0.3),
  ('moe-cgdct', 'otaku-register', 'food', 0.2),
  ('moe-cgdct', 'otaku-register', 'shounen', 0.2),
  ('ecchi-fanservice', 'otaku-register', 'genre:ecchi', 1),
  ('ecchi-fanservice', 'otaku-register', 'genre:hentai', 0.8),
  ('ecchi-fanservice', 'otaku-register', 'nudity', 0.7),
  ('ecchi-fanservice', 'otaku-register', 'female harem', 0.7),
  ('ecchi-fanservice', 'otaku-register', 'large breasts', 0.6),
  ('ecchi-fanservice', 'otaku-register', 'male harem', 0.5),
  ('ecchi-fanservice', 'otaku-register', 'mixed gender harem', 0.4),
  ('ecchi-fanservice', 'otaku-register', 'monster girl', 0.4),
  ('ecchi-fanservice', 'otaku-register', 'flat chest', 0.4),
  ('ecchi-fanservice', 'otaku-register', 'teens'' love', 0.4),
  ('ecchi-fanservice', 'otaku-register', 'succubus', 0.3),
  ('ecchi-fanservice', 'otaku-register', 'virginity', 0.3),
  ('ecchi-fanservice', 'otaku-register', 'school', 0.2),
  ('ecchi-fanservice', 'otaku-register', 'genre:fantasy', 0.2),
  ('ecchi-fanservice', 'otaku-register', 'genre:comedy', 0.2),
  ('ecchi-fanservice', 'otaku-register', 'genre:romance', 0.2),
  ('gag-short-form', 'otaku-register', '4-koma', 1),
  ('gag-short-form', 'otaku-register', 'short-form chapter', 1),
  ('gag-short-form', 'otaku-register', 'surreal comedy', 0.8),
  ('gag-short-form', 'otaku-register', 'slapstick', 0.7),
  ('gag-short-form', 'otaku-register', 'genre:comedy', 0.7),
  ('gag-short-form', 'otaku-register', 'parody', 0.6),
  ('gag-short-form', 'otaku-register', 'manzai', 0.6),
  ('gag-short-form', 'otaku-register', 'chibi', 0.6),
  ('gag-short-form', 'otaku-register', 'meta', 0.5),
  ('gag-short-form', 'otaku-register', 'episodic', 0.5),
  ('gag-short-form', 'otaku-register', 'anthology', 0.4),
  ('gag-short-form', 'otaku-register', 'school', 0.3),
  ('gag-short-form', 'otaku-register', 'no dialogue', 0.3),
  ('gag-short-form', 'otaku-register', 'cute girls doing cute things', 0.3),
  ('gag-short-form', 'otaku-register', 'otaku culture', 0.3),
  ('gag-short-form', 'otaku-register', 'primarily teen cast', 0.2),
  ('seinen-drama', 'seinen-alternative', 'seinen', 1),
  ('seinen-drama', 'seinen-alternative', 'genre:drama', 0.8),
  ('seinen-drama', 'seinen-alternative', 'primarily adult cast', 0.8),
  ('seinen-drama', 'seinen-alternative', 'philosophy', 0.7),
  ('seinen-drama', 'seinen-alternative', 'josei', 0.6),
  ('seinen-drama', 'seinen-alternative', 'coming of age', 0.6),
  ('seinen-drama', 'seinen-alternative', 'urban', 0.5),
  ('seinen-drama', 'seinen-alternative', 'hikikomori', 0.5),
  ('seinen-drama', 'seinen-alternative', 'denpa', 0.5),
  ('seinen-drama', 'seinen-alternative', 'suicide', 0.4),
  ('seinen-drama', 'seinen-alternative', 'psychosexual', 0.4),
  ('seinen-drama', 'seinen-alternative', 'college', 0.4),
  ('seinen-drama', 'seinen-alternative', 'unrequited love', 0.4),
  ('seinen-drama', 'seinen-alternative', 'bullying', 0.4),
  ('seinen-drama', 'seinen-alternative', 'estranged family', 0.4),
  ('seinen-drama', 'seinen-alternative', 'shogi', 0.4),
  ('seinen-drama', 'seinen-alternative', 'genre:slice of life', 0.4),
  ('seinen-drama', 'seinen-alternative', 'tragedy', 0.4),
  ('seinen-drama', 'seinen-alternative', 'band', 0.3),
  ('seinen-drama', 'seinen-alternative', 'genre:romance', 0.3),
  ('seinen-drama', 'seinen-alternative', 'genre:psychological', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'gekiga', 1),
  ('gekiga-alternative', 'seinen-alternative', 'autobiographical', 0.8),
  ('gekiga-alternative', 'seinen-alternative', 'seinen', 0.7),
  ('gekiga-alternative', 'seinen-alternative', 'biographical', 0.6),
  ('gekiga-alternative', 'seinen-alternative', 'non-fiction', 0.6),
  ('gekiga-alternative', 'seinen-alternative', 'historical', 0.5),
  ('gekiga-alternative', 'seinen-alternative', 'philosophy', 0.5),
  ('gekiga-alternative', 'seinen-alternative', 'noir', 0.5),
  ('gekiga-alternative', 'seinen-alternative', 'genre:drama', 0.5),
  ('gekiga-alternative', 'seinen-alternative', 'religion', 0.4),
  ('gekiga-alternative', 'seinen-alternative', 'war', 0.4),
  ('gekiga-alternative', 'seinen-alternative', 'crime', 0.4),
  ('gekiga-alternative', 'seinen-alternative', 'tragedy', 0.4),
  ('gekiga-alternative', 'seinen-alternative', 'ero guro', 0.4),
  ('gekiga-alternative', 'seinen-alternative', 'psychosexual', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'denpa', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'delinquents', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'politics', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'anthology', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'homeless', 0.3),
  ('gekiga-alternative', 'seinen-alternative', 'drugs', 0.2),
  ('gekiga-alternative', 'seinen-alternative', 'genre:horror', 0.2),
  ('gekiga-alternative', 'seinen-alternative', 'suicide', 0.2),
  ('kids-family', 'young', 'kids', 1),
  ('kids-family', 'young', 'primarily child cast', 0.9),
  ('kids-family', 'young', 'educational', 0.7),
  ('kids-family', 'young', 'creature taming', 0.7),
  ('kids-family', 'young', 'youkai', 0.6),
  ('kids-family', 'young', 'primarily animal cast', 0.6),
  ('kids-family', 'young', 'anthropomorphism', 0.6),
  ('kids-family', 'young', 'genre:adventure', 0.5),
  ('kids-family', 'young', 'genre:comedy', 0.5),
  ('kids-family', 'young', 'episodic', 0.5),
  ('kids-family', 'young', 'genre:fantasy', 0.4),
  ('kids-family', 'young', 'family life', 0.4),
  ('kids-family', 'young', 'animals', 0.4),
  ('kids-family', 'young', 'genre:mahou shoujo', 0.4),
  ('kids-family', 'young', 'rural', 0.3),
  ('kids-family', 'young', 'robots', 0.3),
  ('kids-family', 'young', 'card battle', 0.3),
  ('kids-family', 'young', 'henshin', 0.3),
  ('kids-family', 'young', 'superhero', 0.3),
  ('kids-family', 'young', 'magic', 0.3),
  ('kids-family', 'young', 'school', 0.3),
  ('kids-family', 'young', 'genre:slice of life', 0.3)
on conflict (realm, tag_key) do update set
  family = excluded.family,
  weight = excluded.weight;

-- ---------------------------------------------------------------------------
-- 5) Validation: every signature tag_key must resolve against the live
--    vocabulary (lower(tags.name) or 'genre:'||lower(genre) from anime/manga).
--    Raises one WARNING per miss (visible in migration logs, non-fatal) and a
--    NOTICE when clean, so a bad key surfaces without failing the push.
-- ---------------------------------------------------------------------------
do $$
declare
  v_missing record;
  v_count int := 0;
begin
  for v_missing in
    with vocab as (
      select lower(t.name) as tag_key from public.tags t
      union
      select 'genre:' || lower(g.genre)
      from (
        select unnest(a.genres) as genre from public.anime a
        union
        select unnest(m.genres) as genre from public.manga m
      ) g
      where g.genre is not null
    )
    select rs.realm, rs.tag_key
    from public.realm_signatures rs
    left join vocab v using (tag_key)
    where v.tag_key is null
    order by rs.realm, rs.tag_key
  loop
    v_count := v_count + 1;
    raise warning 'realm_signatures: unknown tag_key ''%'' (realm ''%'') — not in tags/genre vocabulary', v_missing.tag_key, v_missing.realm;
  end loop;
  if v_count = 0 then
    raise notice 'realm_signatures: all % signature rows resolved against tags/genre vocabulary', (select count(*) from public.realm_signatures);
  end if;
end $$;

commit;
